;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 5
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env15
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env12,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env1,@env8,@env15
	.byte $00
	.byte $30 ;instrument $06
	.word @env2,@env10,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env2,@env9,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env2,@env11,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env5,@env13,@env0
	.byte $00
	.byte $b0 ;instrument $0d
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env6,@env14,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c6,$c6,$c5,$c4,$c3,$09,$c2,$08,$c1,$0f,$c0,$00,$0a
@env3:
	.byte $cc,$ca,$c9,$c7,$c6,$c5,$c4,$c4,$c3,$c3,$c2,$02,$c1,$03,$c9,$c7
	.byte $c6,$c5,$c4,$c3,$02,$c2,$03,$c1,$02,$c4,$c3,$c3,$c2,$03,$c1,$04
	.byte $c0,$00,$20
@env4:
	.byte $c1,$c2,$c3,$c4,$00,$03
@env5:
	.byte $c8,$00,$00
@env6:
	.byte $c9,$c7,$c6,$c4,$c3,$c2,$c1,$c0,$00,$07
@env7:
	.byte $cb,$c9,$c7,$c5,$c4,$c2,$c1,$c1,$c0,$00,$08
@env8:
	.byte $c0,$c0,$c5,$c5,$c7,$c7,$00,$00
@env9:
	.byte $c0,$02,$c3,$02,$c7,$c7,$c7,$00,$00
@env10:
	.byte $c0,$02,$c4,$02,$c7,$c7,$c7,$00,$00
@env11:
	.byte $c0,$02,$c3,$02,$c8,$c8,$c8,$00,$00
@env12:
	.byte $c0,$02,$c2,$02,$c7,$c7,$c7,$00,$00
@env13:
	.byte $cc,$c0,$00,$01
@env14:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env15:
	.byte $c0,$0b,$c1,$c2,$c3,$c4,$c3,$c2,$c1,$c0,$00,$02


@song0ch0:
	.byte $fb,$10
@song0ch0loop:
@ref0:
	.byte $88,$58,$83,$4e,$83,$52,$91,$60,$83,$5c,$83,$58,$91
@ref1:
	.byte $4e,$83,$60,$83,$4f,$52,$8d,$58,$83,$4e,$83,$52,$91
@ref2:
	.byte $58,$83,$4e,$83,$52,$91,$60,$83,$5c,$83,$58,$91
	.byte $ff,$0d
	.word @ref1
@ref4:
	.byte $58,$89,$5c,$52,$8f,$62,$89,$60,$5c,$83,$61,$63,$66,$81
@ref5:
	.byte $60,$89,$4e,$52,$8d,$4e,$53,$53,$59,$60,$4e,$8f
	.byte $ff,$0c
	.word @ref2
	.byte $ff,$0d
	.word @ref1
	.byte $ff,$0c
	.word @ref2
	.byte $ff,$0d
	.word @ref1
	.byte $ff,$0e
	.word @ref4
	.byte $ff,$0c
	.word @ref5
@ref12:
	.byte $00,$9d
@ref13:
	.byte $9f
@ref14:
	.byte $90,$4e,$4e,$4a,$4a,$4e,$52,$54,$52,$4e,$4e,$4a,$4a,$4e,$52,$5c
	.byte $5e
@ref15:
	.byte $4e,$4e,$4a,$4a,$4e,$54,$52,$50,$4e,$4e,$4a,$4a,$4e,$52,$5c,$5e
@ref16:
	.byte $88,$58,$83,$59,$5e,$5c,$58,$54,$83,$54,$83,$4f,$5e,$83,$5e,$83
	.byte $4f,$5c,$83,$5c,$83,$4e,$81
@ref17:
	.byte $58,$83,$58,$83,$53,$54,$83,$54,$83,$4f,$52,$83,$52,$83,$4d,$4e
	.byte $83,$4e,$83,$46,$40
@ref18:
	.byte $58,$83,$59,$5e,$5c,$58,$54,$83,$54,$83,$4f,$5e,$83,$5e,$83,$4f
	.byte $5c,$83,$5c,$83,$4e,$81
	.byte $ff,$15
	.word @ref17
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref20:
	.byte $00,$bd
@ref21:
	.byte $bf
@ref22:
	.byte $00,$bd
@ref23:
	.byte $bf
@ref24:
	.byte $88,$66,$89,$6a,$60,$8f,$6a,$89,$66,$66,$8f
@ref25:
	.byte $66,$89,$4e,$60,$8d,$5c,$5d,$61,$63,$66,$5c,$8f
@ref26:
	.byte $00,$bd
@ref27:
	.byte $bf
@ref28:
	.byte $00,$bd
@ref29:
	.byte $bf
@ref30:
	.byte $66,$89,$6a,$60,$8f,$6a,$89,$66,$66,$8f
	.byte $ff,$0c
	.word @ref25
@ref32:
	.byte $8a,$4f,$4e,$4e,$83,$37,$4f,$4e,$4e,$83,$36,$81
@ref33:
	.byte $8c,$4f,$4e,$4e,$83,$37,$8a,$4f,$4e,$4e,$83,$36,$81
@ref34:
	.byte $4f,$4e,$4e,$83,$37,$4f,$4e,$4e,$83,$36,$81
	.byte $ff,$0b
	.word @ref33
@ref36:
	.byte $86,$51,$50,$51,$38,$51,$8a,$4f,$4e,$4f,$36,$4f,$86,$47,$46,$47
	.byte $5e,$47,$4f,$4e,$4f,$36,$4e,$81
@ref37:
	.byte $8a,$59,$58,$59,$40,$59,$4f,$4e,$4f,$36,$4f,$86,$45,$44,$45,$5c
	.byte $45,$8a,$4f,$36,$4f,$36,$4e,$36
	.byte $ff,$15
	.word @ref36
	.byte $ff,$15
	.word @ref37
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref40:
	.byte $80,$28,$83,$40,$83,$22,$85,$3a,$22,$3a,$85,$28,$83,$40,$83,$22
	.byte $85,$3a,$22,$3a,$85
@ref41:
	.byte $28,$83,$40,$83,$22,$85,$3a,$22,$3a,$85,$28,$83,$40,$83,$22,$85
	.byte $3a,$40,$3a,$85
@ref42:
	.byte $28,$83,$40,$83,$22,$85,$3a,$22,$3a,$85,$28,$83,$40,$83,$22,$85
	.byte $3a,$22,$3a,$85
	.byte $ff,$14
	.word @ref41
@ref44:
	.byte $29,$31,$37,$40,$3a,$83,$37,$31,$29,$2d,$33,$3b,$44,$3e,$83,$37
	.byte $49,$44,$81
	.byte $ff,$13
	.word @ref44
	.byte $ff,$14
	.word @ref42
	.byte $ff,$14
	.word @ref41
	.byte $ff,$14
	.word @ref42
	.byte $ff,$14
	.word @ref41
	.byte $ff,$13
	.word @ref44
	.byte $ff,$13
	.word @ref44
@ref52:
	.byte $36,$89,$3d,$36,$89,$3c,$81
@ref53:
	.byte $46,$89,$3d,$36,$89,$32,$81
	.byte $ff,$07
	.word @ref52
	.byte $ff,$07
	.word @ref53
@ref56:
	.byte $38,$89,$28,$2e,$36,$89,$24,$2c,$2e,$89,$24,$2e,$36,$8d
@ref57:
	.byte $28,$83,$1e,$28,$1e,$2e,$28,$24,$83,$1e,$24,$1e,$2c,$24,$22,$83
	.byte $2c,$34,$2c,$22,$1c,$1e,$83,$2d,$1e,$83
	.byte $ff,$0e
	.word @ref56
	.byte $ff,$1a
	.word @ref57
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref60:
	.byte $94,$1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09
	.byte $1b,$08,$1b,$08,$08,$81
@ref61:
	.byte $1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b
	.byte $08,$1b,$08,$08,$08
@ref62:
	.byte $1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b
	.byte $08,$1b,$08,$08,$81
	.byte $ff,$15
	.word @ref61
	.byte $ff,$15
	.word @ref62
	.byte $ff,$15
	.word @ref61
	.byte $ff,$15
	.word @ref62
	.byte $ff,$15
	.word @ref61
	.byte $ff,$15
	.word @ref62
	.byte $ff,$15
	.word @ref61
	.byte $ff,$15
	.word @ref62
	.byte $ff,$15
	.word @ref61
@ref72:
	.byte $1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$08,$81
@ref73:
	.byte $1b,$08,$1a,$83,$09,$1b,$08,$1b,$08,$08,$81
	.byte $ff,$0b
	.word @ref72
	.byte $ff,$0b
	.word @ref73
	.byte $ff,$15
	.word @ref62
	.byte $ff,$15
	.word @ref61
	.byte $ff,$15
	.word @ref62
	.byte $ff,$15
	.word @ref61
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref80:
	.byte $bf
@ref81:
	.byte $bf
@ref82:
	.byte $bf
@ref83:
	.byte $bf
@ref84:
	.byte $bf
@ref85:
	.byte $bf
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $bf
@ref90:
	.byte $bf
@ref91:
	.byte $bf
@ref92:
	.byte $9f
@ref93:
	.byte $9f
@ref94:
	.byte $9f
@ref95:
	.byte $9f
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref100:
	.byte $8e,$43,$41,$39,$33,$2b,$29,$2f,$33,$43,$41,$39,$33,$2b,$29,$2f
	.byte $32,$81
@ref101:
	.byte $3f,$3d,$35,$2f,$27,$25,$2b,$2f,$3f,$3d,$35,$2f,$27,$25,$2b,$2e
	.byte $81
@ref102:
	.byte $3b,$39,$31,$2b,$23,$21,$27,$2b,$3b,$39,$31,$2b,$23,$21,$27,$2a
	.byte $81
	.byte $ff,$11
	.word @ref101
@ref104:
	.byte $43,$41,$39,$33,$2b,$29,$2f,$33,$43,$41,$39,$33,$2b,$29,$2f,$32
	.byte $81
	.byte $ff,$11
	.word @ref101
	.byte $ff,$11
	.word @ref102
	.byte $ff,$11
	.word @ref102
	.byte $ff,$11
	.word @ref104
	.byte $ff,$11
	.word @ref101
	.byte $ff,$11
	.word @ref102
	.byte $ff,$11
	.word @ref102
@ref112:
	.byte $5b,$51,$4d,$47,$43,$3f,$43,$47,$5b,$51,$4d,$47,$43,$3f,$43,$46
	.byte $81
	.byte $ff,$11
	.word @ref112
	.byte $ff,$11
	.word @ref112
	.byte $ff,$11
	.word @ref112
@ref116:
	.byte $42,$b5,$42,$85
@ref117:
	.byte $3e,$85,$42,$8d,$3e,$9d,$3b,$3e,$81
@ref118:
	.byte $42,$85,$3a,$8d,$3a,$a1,$3a,$81
@ref119:
	.byte $3e,$8d,$3c,$8d,$3e,$8d,$42,$8d
@ref120:
	.byte $42,$b5,$42,$85
	.byte $ff,$09
	.word @ref117
@ref122:
	.byte $42,$8d,$3b,$3e,$89,$3a,$99,$3a,$81
@ref123:
	.byte $42,$8d,$3e,$8d,$42,$8d,$46,$8d
@ref124:
	.byte $5a,$85,$50,$85,$5b,$50,$89,$5a,$85,$50,$85,$5b,$50,$89
@ref125:
	.byte $5a,$85,$50,$85,$5b,$50,$89,$5a,$85,$50,$85,$5b,$5e,$89
	.byte $ff,$0e
	.word @ref124
	.byte $ff,$0e
	.word @ref125
	.byte $ff,$0e
	.word @ref124
	.byte $ff,$0e
	.word @ref125
	.byte $ff,$0e
	.word @ref124
	.byte $ff,$0e
	.word @ref125
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref132:
	.byte $8e,$5b,$59,$51,$4b,$43,$41,$47,$4b,$5b,$59,$51,$4b,$43,$41,$47
	.byte $4a,$81
@ref133:
	.byte $57,$55,$4d,$47,$3f,$3d,$43,$47,$57,$55,$4d,$47,$3f,$3d,$43,$46
	.byte $81
@ref134:
	.byte $53,$51,$49,$43,$3b,$39,$3f,$43,$53,$51,$49,$43,$3b,$39,$3f,$42
	.byte $81
	.byte $ff,$11
	.word @ref133
@ref136:
	.byte $90,$42,$91,$40,$85,$42,$8d,$41,$43,$40,$89
@ref137:
	.byte $3e,$95,$3d,$3e,$99,$3c,$85
@ref138:
	.byte $3a,$8d,$38,$89,$39,$3a,$8d,$34,$89,$38,$81
@ref139:
	.byte $3e,$8d,$3c,$89,$3d,$3e,$8d,$42,$8d
@ref140:
	.byte $42,$91,$40,$85,$42,$8d,$41,$43,$40,$89
	.byte $ff,$07
	.word @ref137
	.byte $ff,$0b
	.word @ref138
	.byte $ff,$09
	.word @ref139
@ref144:
	.byte $8e,$5a,$85,$50,$85,$5a,$85,$01,$5b,$01,$5b,$01,$51,$5b,$5f,$50
	.byte $85
@ref145:
	.byte $5a,$85,$50,$85,$5a,$85,$01,$5b,$01,$5b,$01,$51,$5b,$5f,$50,$85
	.byte $ff,$10
	.word @ref145
	.byte $ff,$10
	.word @ref145
@ref148:
	.byte $90,$42,$b5,$42,$85
	.byte $ff,$09
	.word @ref117
	.byte $ff,$08
	.word @ref118
	.byte $ff,$08
	.word @ref119
@ref152:
	.byte $42,$b5,$42,$85
	.byte $ff,$09
	.word @ref117
	.byte $ff,$09
	.word @ref122
	.byte $ff,$08
	.word @ref123
@ref156:
	.byte $38,$85,$42,$85,$47,$42,$89,$46,$85,$42,$85,$38,$85,$42,$85
@ref157:
	.byte $38,$85,$42,$85,$47,$42,$89,$46,$85,$42,$85,$46,$85,$48,$85
@ref158:
	.byte $4c,$95,$4d,$49,$46,$9d
@ref159:
	.byte $4c,$95,$4d,$49,$46,$8d,$48,$8d
	.byte $ff,$0f
	.word @ref156
	.byte $ff,$0f
	.word @ref157
	.byte $ff,$06
	.word @ref158
@ref163:
	.byte $42,$8d,$46,$8d,$48,$8d,$4c,$8d
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref164:
	.byte $00,$bd
@ref165:
	.byte $bf
@ref166:
	.byte $bf
@ref167:
	.byte $9f,$80,$6f,$6d,$65,$5f,$57,$55,$5b,$5e,$81
@ref168:
	.byte $2b,$01,$2a,$89,$29,$01,$2b,$01,$2a,$85,$27,$2b,$27,$21,$1c,$81
@ref169:
	.byte $20,$85,$21,$2e,$89,$21,$20,$85,$1d,$27,$01,$27,$25,$1d,$2e,$81
@ref170:
	.byte $22,$85,$22,$85,$23,$3b,$22,$85,$22,$85,$22,$85,$23,$3b,$22,$85
@ref171:
	.byte $26,$85,$26,$85,$27,$3f,$26,$85,$26,$85,$26,$85,$27,$3f,$27,$42
	.byte $81
	.byte $ff,$10
	.word @ref168
	.byte $ff,$10
	.word @ref169
	.byte $ff,$10
	.word @ref170
	.byte $ff,$11
	.word @ref171
@ref176:
	.byte $2b,$2b,$2b,$2b,$43,$2b,$2b,$2b,$2b,$2b,$2b,$2b,$43,$2b,$2b,$42
	.byte $81
@ref177:
	.byte $27,$27,$27,$27,$3f,$27,$27,$27,$27,$27,$27,$27,$3f,$27,$27,$3e
	.byte $81
@ref178:
	.byte $23,$23,$23,$23,$3b,$23,$23,$23,$23,$23,$23,$23,$3b,$23,$23,$3a
	.byte $81
	.byte $ff,$11
	.word @ref177
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref177
	.byte $ff,$11
	.word @ref178
	.byte $ff,$11
	.word @ref177
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref177
	.byte $ff,$11
	.word @ref178
	.byte $ff,$11
	.word @ref177
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref177
	.byte $ff,$11
	.word @ref178
	.byte $ff,$11
	.word @ref177
	.byte $ff,$11
	.word @ref176
	.byte $ff,$11
	.word @ref177
	.byte $ff,$11
	.word @ref178
	.byte $ff,$11
	.word @ref177
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref196:
	.byte $bf
@ref197:
	.byte $bf
@ref198:
	.byte $bf
@ref199:
	.byte $bf
@ref200:
	.byte $92,$21,$94,$1b,$92,$21,$94,$1b,$21,$92,$21,$94,$1b,$92,$21,$94
	.byte $1b,$92,$21,$94,$1b,$92,$21,$94,$21,$92,$21,$94,$1b,$92,$20,$81
@ref201:
	.byte $21,$21,$94,$1b,$92,$21,$94,$21,$92,$21,$94,$1b,$92,$21,$94,$1b
	.byte $92,$21,$21,$21,$94,$21,$92,$21,$94,$21,$20,$81
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
@ref219:
	.byte $21,$21,$94,$1b,$92,$21,$94,$21,$92,$21,$94,$1b,$92,$21,$94,$21
	.byte $21,$21,$21,$92,$21,$21,$94,$21,$20,$81
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref219
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref201
	.byte $ff,$11
	.word @ref200
	.byte $ff,$11
	.word @ref219
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref228:
	.byte $bf
@ref229:
	.byte $bf
@ref230:
	.byte $bf
@ref231:
	.byte $bf
@ref232:
	.byte $bf
@ref233:
	.byte $bf
@ref234:
	.byte $bf
@ref235:
	.byte $bf
@ref236:
	.byte $bf
@ref237:
	.byte $bf
@ref238:
	.byte $bf
@ref239:
	.byte $bf
@ref240:
	.byte $bf
@ref241:
	.byte $bf
@ref242:
	.byte $bf
@ref243:
	.byte $bf
@ref244:
	.byte $bf
@ref245:
	.byte $bf
@ref246:
	.byte $bf
@ref247:
	.byte $bf
@ref248:
	.byte $bf
@ref249:
	.byte $bf
@ref250:
	.byte $bf
@ref251:
	.byte $bf
@ref252:
	.byte $bf
@ref253:
	.byte $bf
@ref254:
	.byte $bf
@ref255:
	.byte $bf
@ref256:
	.byte $bf
@ref257:
	.byte $bf
@ref258:
	.byte $bf
@ref259:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$08
@ref260:
	.byte $00,$bd
@ref261:
	.byte $00,$bd
@song2ch0loop:
@ref262:
	.byte $88,$5c,$62,$6a,$85,$5c,$62,$6a,$8d,$5c,$60,$6a,$85,$5c,$66,$6a
	.byte $8d
@ref263:
	.byte $5c,$62,$6a,$85,$5c,$62,$6a,$8d,$5c,$60,$6a,$85,$5c,$66,$6a,$8d
	.byte $ff,$10
	.word @ref263
	.byte $ff,$10
	.word @ref263
@ref266:
	.byte $60,$6a,$6e,$85,$60,$6a,$70,$8d,$5c,$64,$6a,$85,$5c,$64,$6e,$8d
	.byte $ff,$10
	.word @ref266
	.byte $ff,$10
	.word @ref266
	.byte $ff,$10
	.word @ref266
	.byte $ff,$10
	.word @ref263
	.byte $ff,$10
	.word @ref263
	.byte $ff,$10
	.word @ref263
	.byte $ff,$10
	.word @ref263
	.byte $ff,$10
	.word @ref266
	.byte $ff,$10
	.word @ref266
	.byte $ff,$10
	.word @ref266
	.byte $ff,$10
	.word @ref266
@ref278:
	.byte $5c,$64,$6a,$85,$5c,$64,$6e,$8d,$56,$5c,$6a,$85,$56,$5c,$64,$8d
	.byte $ff,$10
	.word @ref278
	.byte $ff,$10
	.word @ref278
	.byte $ff,$10
	.word @ref278
@ref282:
	.byte $00,$bd
@ref283:
	.byte $af,$44,$44,$44,$85,$5c,$5c
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref284:
	.byte $00,$bd
@ref285:
	.byte $00,$bd
@song2ch1loop:
@ref286:
	.byte $8a,$44,$89,$44,$91,$82,$44,$89,$8a,$44,$8d,$86,$40,$81
	.byte $ff,$0a
	.word @ref286
	.byte $ff,$0a
	.word @ref286
	.byte $ff,$0a
	.word @ref286
@ref290:
	.byte $90,$49,$3a,$85,$49,$3a,$85,$48,$85,$4d,$48,$85,$4f,$4f,$4d,$49
	.byte $4c,$81
@ref291:
	.byte $49,$3a,$85,$49,$3a,$85,$48,$85,$45,$40,$85,$3a,$85,$41,$3b,$40
	.byte $81
@ref292:
	.byte $49,$3a,$85,$49,$3a,$85,$48,$85,$4d,$48,$85,$4f,$4f,$4d,$49,$4c
	.byte $81
	.byte $ff,$11
	.word @ref291
	.byte $ff,$0a
	.word @ref286
	.byte $ff,$0a
	.word @ref286
	.byte $ff,$0a
	.word @ref286
	.byte $ff,$0a
	.word @ref286
	.byte $ff,$11
	.word @ref290
	.byte $ff,$11
	.word @ref291
	.byte $ff,$11
	.word @ref292
	.byte $ff,$11
	.word @ref291
@ref302:
	.byte $45,$3b,$43,$44,$91,$52,$85,$4e,$85,$4d,$49,$45,$48,$81
@ref303:
	.byte $45,$3b,$43,$44,$91,$52,$85,$4e,$85,$56,$85,$52,$85
	.byte $ff,$0e
	.word @ref302
	.byte $ff,$0d
	.word @ref303
	.byte $ff,$0a
	.word @ref286
@ref307:
	.byte $8a,$44,$89,$44,$91,$82,$44,$89,$8a,$44,$8d,$90,$40,$81
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref308:
	.byte $80,$2c,$89,$32,$91,$30,$89,$36,$91
@ref309:
	.byte $2c,$89,$32,$91,$30,$89,$36,$91
@song2ch2loop:
	.byte $ff,$08
	.word @ref308
	.byte $ff,$08
	.word @ref309
	.byte $ff,$08
	.word @ref309
	.byte $ff,$08
	.word @ref309
@ref314:
	.byte $30,$89,$3a,$91,$44,$85,$35,$2c,$8d,$44,$81
	.byte $ff,$0b
	.word @ref314
	.byte $ff,$0b
	.word @ref314
	.byte $ff,$0b
	.word @ref314
	.byte $ff,$08
	.word @ref309
	.byte $ff,$08
	.word @ref309
	.byte $ff,$08
	.word @ref309
	.byte $ff,$08
	.word @ref309
	.byte $ff,$0b
	.word @ref314
	.byte $ff,$0b
	.word @ref314
	.byte $ff,$0b
	.word @ref314
	.byte $ff,$0b
	.word @ref314
@ref326:
	.byte $2d,$3b,$35,$2d,$3b,$35,$2c,$85,$23,$2d,$35,$27,$2d,$35,$3b,$3e
	.byte $81
	.byte $ff,$11
	.word @ref326
	.byte $ff,$11
	.word @ref326
	.byte $ff,$11
	.word @ref326
	.byte $ff,$08
	.word @ref309
@ref331:
	.byte $2c,$89,$32,$91,$30,$89,$37,$00,$8d
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref332:
	.byte $bf
@ref333:
	.byte $bf
@song2ch3loop:
@ref334:
	.byte $92,$21,$21,$94,$0d,$92,$20,$94,$0c,$92,$20,$94,$0c,$92,$21,$94
	.byte $0c,$85,$92,$21,$21,$94,$0d,$92,$20,$94,$0c,$92,$20,$94,$0c,$92
	.byte $21,$94,$0c,$20,$04,$08
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
	.byte $ff,$16
	.word @ref334
@ref355:
	.byte $92,$21,$21,$94,$0d,$92,$20,$94,$0c,$92,$20,$94,$0c,$92,$21,$94
	.byte $0c,$85,$92,$21,$21,$94,$0d,$92,$20,$94,$0c,$92,$20,$85,$94,$0d
	.byte $04,$81
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref356:
	.byte $bf
@ref357:
	.byte $bf
@song2ch4loop:
@ref358:
	.byte $bf
@ref359:
	.byte $bf
@ref360:
	.byte $bf
@ref361:
	.byte $bf
@ref362:
	.byte $bf
@ref363:
	.byte $bf
@ref364:
	.byte $bf
@ref365:
	.byte $bf
@ref366:
	.byte $bf
@ref367:
	.byte $bf
@ref368:
	.byte $bf
@ref369:
	.byte $bf
@ref370:
	.byte $bf
@ref371:
	.byte $bf
@ref372:
	.byte $bf
@ref373:
	.byte $bf
@ref374:
	.byte $bf
@ref375:
	.byte $bf
@ref376:
	.byte $bf
@ref377:
	.byte $bf
@ref378:
	.byte $bf
@ref379:
	.byte $bf
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$0a
@song3ch0loop:
@ref380:
	.byte $00,$f9,$83
@ref381:
	.byte $00,$f9,$83
@ref382:
	.byte $8e,$4b,$55,$55,$55,$4f,$47,$47,$01,$45,$4b,$45,$3d,$40,$44,$40
	.byte $3c,$41,$01,$4b,$55,$55,$55,$4f,$47,$47,$01,$44,$4a,$44,$3c,$41
	.byte $41,$3c,$85,$00,$85
@ref383:
	.byte $4b,$55,$55,$55,$4f,$47,$47,$01,$45,$4b,$45,$3d,$40,$44,$40,$3c
	.byte $41,$01,$4b,$55,$55,$55,$4f,$47,$47,$01,$44,$4a,$44,$3c,$41,$41
	.byte $3c,$85,$00,$85
@ref384:
	.byte $00,$f9,$83
	.byte $ff,$24
	.word @ref383
	.byte $ff,$24
	.word @ref383
@ref387:
	.byte $55,$55,$4f,$4f,$55,$55,$4f,$01,$53,$53,$4b,$4b,$53,$53,$4b,$01
	.byte $55,$55,$4f,$4f,$55,$55,$4e,$83,$4e,$53,$4e,$4a,$4f,$4a,$48,$4a
	.byte $85,$33,$00,$81
@ref388:
	.byte $bf
	.byte $ff,$24
	.word @ref383
	.byte $ff,$24
	.word @ref383
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref391:
	.byte $00,$f9,$83
@ref392:
	.byte $90,$3c,$85,$44,$85,$46,$85,$4e,$85,$4a,$85,$44,$85,$41,$3d,$3b
	.byte $41,$3c,$85,$44,$85,$46,$85,$4e,$85,$4b,$3d,$41,$33,$3c,$8d
@ref393:
	.byte $00,$f9,$83
@ref394:
	.byte $3c,$85,$44,$85,$46,$85,$4e,$85,$4a,$85,$44,$85,$41,$3d,$3b,$41
	.byte $3c,$85,$44,$85,$46,$85,$4e,$85,$4b,$3d,$41,$33,$3c,$8d
@ref395:
	.byte $00,$f9,$83
	.byte $ff,$1e
	.word @ref394
	.byte $ff,$1e
	.word @ref394
@ref398:
	.byte $3d,$37,$44,$85,$3d,$37,$44,$85,$3b,$33,$40,$85,$3b,$33,$46,$85
	.byte $3d,$37,$45,$4b,$3d,$37,$45,$4b,$33,$3b,$41,$49,$4a,$85,$00,$85
@ref399:
	.byte $b9,$32,$36,$3a
	.byte $ff,$1e
	.word @ref394
	.byte $ff,$1e
	.word @ref394
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref402:
	.byte $80,$25,$01,$32,$85,$2f,$01,$24,$85,$2c,$00,$24,$00,$32,$85,$29
	.byte $1b,$1f,$22,$00,$25,$01,$32,$85,$2f,$01,$24,$85,$24,$00,$1a,$00
	.byte $22,$00,$1a,$00,$24,$85,$1a,$85
@ref403:
	.byte $25,$01,$32,$85,$2f,$01,$24,$85,$2c,$00,$24,$00,$32,$85,$29,$1b
	.byte $1f,$22,$00,$25,$01,$32,$85,$2f,$01,$24,$85,$24,$00,$1a,$00,$22
	.byte $00,$1a,$00,$24,$85,$1a,$85
	.byte $ff,$27
	.word @ref403
	.byte $ff,$27
	.word @ref403
	.byte $ff,$27
	.word @ref403
	.byte $ff,$27
	.word @ref403
	.byte $ff,$27
	.word @ref403
@ref409:
	.byte $8e,$1f,$01,$25,$01,$1f,$01,$25,$01,$23,$01,$29,$01,$23,$01,$1b
	.byte $01,$1f,$01,$25,$01,$1f,$01,$25,$01,$28,$85,$22,$85,$1a,$89,$90
	.byte $1a,$81
@ref410:
	.byte $32,$89,$1b,$32,$8d,$00,$9d
	.byte $ff,$27
	.word @ref402
	.byte $ff,$27
	.word @ref403
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref413:
	.byte $92,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e
	.byte $85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e
	.byte $85
@ref414:
	.byte $1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85
	.byte $1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85
@ref415:
	.byte $02,$85,$12,$85,$02,$85,$13,$03,$02,$85,$12,$85,$03,$13,$03,$03
	.byte $02,$85,$12,$85,$02,$85,$13,$03,$03,$13,$03,$13,$02,$85,$12,$85
	.byte $ff,$20
	.word @ref415
	.byte $ff,$20
	.word @ref414
	.byte $ff,$20
	.word @ref415
	.byte $ff,$20
	.word @ref415
	.byte $ff,$20
	.word @ref415
	.byte $ff,$10
	.word @ref414
	.byte $ff,$20
	.word @ref415
	.byte $ff,$20
	.word @ref415
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref424:
	.byte $f9,$85
@ref425:
	.byte $f9,$85
@ref426:
	.byte $f9,$85
@ref427:
	.byte $f9,$85
@ref428:
	.byte $f9,$85
@ref429:
	.byte $f9,$85
@ref430:
	.byte $f9,$85
@ref431:
	.byte $f9,$85
@ref432:
	.byte $bf
@ref433:
	.byte $f9,$85
@ref434:
	.byte $f9,$85
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$06
@song4ch0loop:
@ref435:
	.byte $f9,$85
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref436:
	.byte $f9,$85
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref437:
	.byte $80,$4b,$53,$59,$61,$63,$61,$59,$53,$4b,$53,$59,$61,$63,$61,$6b
	.byte $63,$41,$49,$4f,$57,$59,$57,$4f,$49,$41,$49,$4f,$57,$59,$61,$67
	.byte $60,$81
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref438:
	.byte $94,$20,$99,$21,$20,$9d,$20,$99,$21,$20,$9d
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref439:
	.byte $f9,$85
	.byte $fd
	.word @song4ch4loop
