// CHR-ROM Map & decos indexes
// Generated by rle53mapchrrom.exe v0.1 20171113
// Copyleft 2017 by The Mojon Twins

// Map # 0 read from level0.map (6x4)

// Definitions

#define MAP_00_CHRROM    3
#define MAP_00_BASE      0x0000
#define MAP_00_W         6
#define MAP_00_H         4
#define MAP_00_MAXPANTS  24

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x005E, 
	MAP_00_BASE + 0x00C8, MAP_00_BASE + 0x0145, 
	MAP_00_BASE + 0x01C2, MAP_00_BASE + 0x0248, 
	MAP_00_BASE + 0x02A7, MAP_00_BASE + 0x0317, 
	MAP_00_BASE + 0x039C, MAP_00_BASE + 0x0410, 
	MAP_00_BASE + 0x0479, MAP_00_BASE + 0x04F7, 
	MAP_00_BASE + 0x056F, MAP_00_BASE + 0x05CE, 
	MAP_00_BASE + 0x0642, MAP_00_BASE + 0x06B7, 
	MAP_00_BASE + 0x0738, MAP_00_BASE + 0x079E, 
	MAP_00_BASE + 0x0811, MAP_00_BASE + 0x088B, 
	MAP_00_BASE + 0x091C, MAP_00_BASE + 0x0994, 
	MAP_00_BASE + 0x0A1C, MAP_00_BASE + 0x0A78
};

// Total screens size in bytes is 2778

// Locks
// These tiles are locks:  15
const unsigned char map_00_locks [] = {
	0x15, 0xaf, 0x16, 0xaf
};

// Map # 1 read from level1.map (8x3)

// Definitions

#define MAP_01_CHRROM    3
#define MAP_01_BASE      0x0ADA
#define MAP_01_W         8
#define MAP_01_H         3
#define MAP_01_MAXPANTS  24

// Screens index

const unsigned int map_01_scr_offsets [] = {
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x0054, 
	MAP_01_BASE + 0x0090, MAP_01_BASE + 0x00CA, 
	MAP_01_BASE + 0x0106, MAP_01_BASE + 0x014F, 
	MAP_01_BASE + 0x018F, MAP_01_BASE + 0x01DD, 
	MAP_01_BASE + 0x0232, MAP_01_BASE + 0x0279, 
	MAP_01_BASE + 0x02AF, MAP_01_BASE + 0x0309, 
	MAP_01_BASE + 0x036F, MAP_01_BASE + 0x03B2, 
	MAP_01_BASE + 0x0401, MAP_01_BASE + 0x0441, 
	MAP_01_BASE + 0x047F, MAP_01_BASE + 0x04D3, 
	MAP_01_BASE + 0x051E, MAP_01_BASE + 0x057F, 
	MAP_01_BASE + 0x05BD, MAP_01_BASE + 0x060B, 
	MAP_01_BASE + 0x065D, MAP_01_BASE + 0x06B8
};

// Total screens size in bytes is 1778

