// CHR-ROM Map & decos indexes
// Generated by rle53mapchrrom.exe v0.1 20171113
// Copyleft 2017 by The Mojon Twins

// Map # 0 read from level0.map (6x4)

// Definitions

#define MAP_00_CHRROM    3
#define MAP_00_BASE      0x0000
#define MAP_00_W         6
#define MAP_00_H         4
#define MAP_00_MAXPANTS  24
#define MAP_00_N_LOCKS   4

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x005E, 
	MAP_00_BASE + 0x00C8, MAP_00_BASE + 0x0145, 
	MAP_00_BASE + 0x01C4, MAP_00_BASE + 0x024A, 
	MAP_00_BASE + 0x02A9, MAP_00_BASE + 0x0319, 
	MAP_00_BASE + 0x039E, MAP_00_BASE + 0x0412, 
	MAP_00_BASE + 0x047B, MAP_00_BASE + 0x04F9, 
	MAP_00_BASE + 0x0571, MAP_00_BASE + 0x05D0, 
	MAP_00_BASE + 0x0644, MAP_00_BASE + 0x06B9, 
	MAP_00_BASE + 0x073A, MAP_00_BASE + 0x07A0, 
	MAP_00_BASE + 0x0813, MAP_00_BASE + 0x088D, 
	MAP_00_BASE + 0x091E, MAP_00_BASE + 0x0996, 
	MAP_00_BASE + 0x0A1E, MAP_00_BASE + 0x0A7A
};

// Total screens size in bytes is 2780

// Locks
// These tiles are locks:  15
const unsigned char map_00_locks [] = {
	0x15, 0xaf, 0x16, 0xaf
};

// Map # 1 read from level1.map (8x3)

// Definitions

#define MAP_01_CHRROM    3
#define MAP_01_BASE      0x0ADC
#define MAP_01_W         8
#define MAP_01_H         3
#define MAP_01_MAXPANTS  24
#define MAP_01_N_LOCKS   0

// Screens index

const unsigned int map_01_scr_offsets [] = {
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x0054, 
	MAP_01_BASE + 0x0090, MAP_01_BASE + 0x00CA, 
	MAP_01_BASE + 0x0106, MAP_01_BASE + 0x014F, 
	MAP_01_BASE + 0x018F, MAP_01_BASE + 0x01DD, 
	MAP_01_BASE + 0x0232, MAP_01_BASE + 0x0279, 
	MAP_01_BASE + 0x02AF, MAP_01_BASE + 0x0309, 
	MAP_01_BASE + 0x036F, MAP_01_BASE + 0x03B2, 
	MAP_01_BASE + 0x0401, MAP_01_BASE + 0x0441, 
	MAP_01_BASE + 0x047F, MAP_01_BASE + 0x04D3, 
	MAP_01_BASE + 0x051E, MAP_01_BASE + 0x057F, 
	MAP_01_BASE + 0x05BD, MAP_01_BASE + 0x060B, 
	MAP_01_BASE + 0x065D, MAP_01_BASE + 0x06B8
};

// Total screens size in bytes is 1778

// Map # 2 read from level2.map (6x4)

// Definitions

#define MAP_02_CHRROM    3
#define MAP_02_BASE      0x11CE
#define MAP_02_W         6
#define MAP_02_H         4
#define MAP_02_MAXPANTS  24
#define MAP_02_N_LOCKS   0

// Screens index

const unsigned int map_02_scr_offsets [] = {
	MAP_02_BASE + 0x0000, MAP_02_BASE + 0x001F, 
	MAP_02_BASE + 0x0052, MAP_02_BASE + 0x0095, 
	MAP_02_BASE + 0x00CF, MAP_02_BASE + 0x00E9, 
	MAP_02_BASE + 0x0110, MAP_02_BASE + 0x013B, 
	MAP_02_BASE + 0x01A1, MAP_02_BASE + 0x01FA, 
	MAP_02_BASE + 0x026A, MAP_02_BASE + 0x02CC, 
	MAP_02_BASE + 0x0306, MAP_02_BASE + 0x035E, 
	MAP_02_BASE + 0x03AB, MAP_02_BASE + 0x041A, 
	MAP_02_BASE + 0x0482, MAP_02_BASE + 0x04D3, 
	MAP_02_BASE + 0x0531, MAP_02_BASE + 0x055F, 
	MAP_02_BASE + 0x05CF, MAP_02_BASE + 0x0626, 
	MAP_02_BASE + 0x0664, MAP_02_BASE + 0x06C6
};

// Total screens size in bytes is 1837

