// Index file to ..\enems.bin
// Generated by binpaster.exe v0.1 20180405
// Copyleft 2018 by The Mojon Twins

#define ENEMS0_H_BIN_OFFS 0
#define ENEMS1_H_BIN_OFFS 336
#define ENEMS2_H_BIN_OFFS 672
#define ENEMS3_H_BIN_OFFS 1008
#define ENEMS4_H_BIN_OFFS 1344

