;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 5
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env22
	.byte $00
	.byte $30 ;instrument $02
	.word @env4,@env17,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env2,@env0,@env22
	.byte $00
	.byte $30 ;instrument $04
	.word @env8,@env21,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env14,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env10,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $09
	.word @env6,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0b
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env7,@env16,@env0
	.byte $00
	.byte $30 ;instrument $0e
	.word @env4,@env18,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env4,@env19,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env4,@env20,@env0
	.byte $00
	.byte $30 ;instrument $11
	.word @env9,@env0,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env13,@env21,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env15,@env0,@env0
	.byte $00
	.byte $30 ;instrument $14
	.word @env11,@env0,@env22
	.byte $00
	.byte $70 ;instrument $15
	.word @env12,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c1,$c2,$c3,$c5,$00,$03
@env2:
	.byte $c1,$c3,$c6,$ca,$00,$03
@env3:
	.byte $cf,$00,$00
@env4:
	.byte $c2,$c3,$c4,$02,$c3,$c3,$c2,$07,$c2,$00,$08
@env5:
	.byte $ca,$c9,$c7,$c4,$c2,$c0,$00,$05
@env6:
	.byte $cd,$cb,$ca,$c9,$c8,$c7,$c7,$c6,$c4,$c3,$c2,$c2,$c1,$c4,$c4,$c3
	.byte $c2,$c2,$c1,$02,$c0,$0a,$c1,$c2,$c1,$06,$c0,$00,$1a
@env7:
	.byte $c2,$c3,$c5,$c6,$c7,$c8,$c9,$03,$c8,$c6,$c4,$c8,$c8,$c8,$00,$0d
@env8:
	.byte $cd,$cb,$c9,$c7,$c5,$c4,$c2,$c1,$c0,$00,$08
@env9:
	.byte $cc,$00,$00
@env10:
	.byte $ca,$c5,$c3,$c2,$c0,$00,$04
@env11:
	.byte $c1,$c3,$c7,$c9,$00,$03
@env12:
	.byte $c9,$07,$c6,$05,$c9,$07,$c9,$00,$06
@env13:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env14:
	.byte $cb,$ca,$c8,$c7,$c4,$c3,$c2,$c1,$c0,$00,$08
@env15:
	.byte $cd,$cc,$ca,$c9,$c7,$c6,$c5,$c3,$c0,$00,$08
@env16:
	.byte $c0,$cc,$cc,$c0,$00,$03
@env17:
	.byte $c0,$c4,$c7,$cc,$00,$00
@env18:
	.byte $bb,$c0,$c3,$c7,$00,$00
@env19:
	.byte $c0,$c3,$c7,$ca,$00,$00
@env20:
	.byte $bb,$be,$c0,$c4,$00,$00
@env21:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env22:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02


@song0ch0:
	.byte $fb,$06
@ref0:
	.byte $8e,$32,$85,$32,$85,$36,$85,$36,$85,$3a,$85,$3a,$85,$36,$83,$3a
	.byte $36,$85
@ref1:
	.byte $32,$85,$32,$85,$36,$85,$36,$85,$3a,$85,$3a,$85,$36,$83,$3a,$36
	.byte $85
@song0ch0loop:
@ref2:
	.byte $94,$32,$9d,$2c,$9d,$28,$9d,$24,$9d
@ref3:
	.byte $28,$9d,$2c,$9d,$28,$89,$2c,$89,$30,$9d,$00,$85
@ref4:
	.byte $2c,$99,$29,$00,$8d,$2e,$85,$24,$85,$8e,$3a,$85,$3a,$85,$3c,$85
	.byte $3c,$85,$3a,$85,$3a,$85,$36,$83,$3a,$36,$85
	.byte $ff,$11
	.word @ref1
	.byte $ff,$08
	.word @ref2
	.byte $ff,$0c
	.word @ref3
	.byte $ff,$1a
	.word @ref4
	.byte $ff,$11
	.word @ref1
@ref10:
	.byte $00,$f9,$83
@ref11:
	.byte $df
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref12:
	.byte $8e,$3a,$85,$3a,$85,$3c,$85,$3c,$85,$40,$85,$40,$85,$3c,$83,$40
	.byte $3c,$85
@ref13:
	.byte $3a,$85,$3a,$85,$3c,$85,$3c,$85,$40,$85,$40,$85,$3c,$83,$40,$3c
	.byte $85
@song0ch1loop:
@ref14:
	.byte $87,$82,$4a,$8d,$44,$85,$3c,$8d,$3d,$41,$44,$8d,$4a,$8d,$44,$85
	.byte $3c,$9d
@ref15:
	.byte $87,$4a,$8d,$44,$85,$3c,$89,$3d,$40,$85,$44,$85,$48,$89,$4a,$89
	.byte $4e,$9d,$4b,$4e,$81
@ref16:
	.byte $50,$85,$4e,$85,$4a,$85,$45,$41,$00,$85,$40,$83,$44,$46,$85,$44
	.byte $85,$41,$4a,$83,$00,$4a,$91,$8e,$40,$85,$40,$85,$3c,$83,$40,$3c
	.byte $85
	.byte $ff,$11
	.word @ref13
	.byte $ff,$11
	.word @ref14
	.byte $ff,$15
	.word @ref15
	.byte $ff,$20
	.word @ref16
	.byte $ff,$11
	.word @ref13
@ref22:
	.byte $87,$94,$32,$00,$33,$3c,$83,$00,$44,$83,$00,$40,$83,$00,$3d,$32
	.byte $99,$32,$00,$33,$3c,$83,$00,$44,$83,$00,$40,$83,$00,$45,$46,$85
	.byte $33,$3d,$40,$81
@ref23:
	.byte $45,$41,$3c,$83,$00,$40,$83,$00,$4a,$8d,$3d,$41,$45,$41,$3c,$8d
	.byte $3d,$41,$45,$41,$3c,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref24:
	.byte $80,$32,$83,$00,$32,$83,$00,$32,$83,$00,$32,$83,$00,$32,$83,$00
	.byte $32,$83,$00,$32,$83,$00,$32,$83,$00
@ref25:
	.byte $32,$83,$00,$32,$83,$00,$32,$83,$00,$32,$83,$00,$32,$83,$00,$32
	.byte $83,$00,$32,$83,$00,$32,$83,$00
@song0ch2loop:
@ref26:
	.byte $82,$1a,$85,$32,$85,$1a,$85,$32,$85,$0c,$85,$24,$85,$0c,$85,$24
	.byte $85,$1a,$85,$32,$85,$1a,$85,$32,$85,$0c,$85,$24,$85,$08,$85,$20
	.byte $85
@ref27:
	.byte $1a,$85,$32,$85,$1a,$85,$32,$85,$0c,$85,$24,$85,$0c,$85,$24,$85
	.byte $1e,$89,$1e,$89,$28,$9d,$80,$1b,$1e,$81
@ref28:
	.byte $82,$0c,$85,$24,$85,$0c,$85,$25,$29,$00,$9d,$80,$32,$83,$00,$32
	.byte $83,$00,$32,$83,$00,$32,$83,$00,$32,$83,$00,$32,$83,$00,$32,$83
	.byte $00,$32,$83,$00
	.byte $ff,$18
	.word @ref25
	.byte $ff,$20
	.word @ref26
	.byte $ff,$19
	.word @ref27
	.byte $ff,$22
	.word @ref28
	.byte $ff,$18
	.word @ref25
@ref34:
	.byte $24,$83,$00,$24,$83,$00,$24,$83,$00,$24,$83,$00,$28,$83,$00,$28
	.byte $83,$00,$2e,$83,$00,$2e,$85,$24,$83,$00,$24,$83,$00,$24,$83,$00
	.byte $24,$83,$00,$28,$83,$00,$28,$83,$00,$2e,$83,$00,$2e,$85
@ref35:
	.byte $24,$83,$00,$24,$83,$00,$32,$83,$00,$32,$83,$00,$24,$83,$00,$24
	.byte $83,$00,$24,$83,$00,$24,$83,$00,$24,$83,$00,$24,$83,$00,$24,$83
	.byte $00,$24,$83,$00
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref36:
	.byte $8a,$08,$85,$88,$16,$85,$8a,$08,$85,$88,$16,$85,$8a,$08,$85,$88
	.byte $16,$85,$8a,$08,$85,$88,$16,$85
	.byte $ff,$10
	.word @ref36
@song0ch3loop:
@ref38:
	.byte $8a,$08,$85,$88,$16,$85,$8a,$08,$85,$88,$16,$85,$8a,$08,$85,$88
	.byte $16,$85,$8a,$08,$85,$88,$16,$85,$8a,$08,$85,$88,$16,$85,$8a,$08
	.byte $85,$88,$16,$85,$8a,$08,$85,$88,$16,$85,$8a,$08,$85,$88,$16,$85
@ref39:
	.byte $8a,$08,$85,$88,$16,$85,$8a,$08,$85,$88,$16,$85,$8a,$08,$85,$88
	.byte $16,$85,$8a,$08,$85,$88,$16,$85,$08,$89,$0c,$89,$10,$9d,$8c,$1f
	.byte $1e,$81
	.byte $ff,$20
	.word @ref38
	.byte $ff,$10
	.word @ref36
	.byte $ff,$20
	.word @ref38
	.byte $ff,$19
	.word @ref39
	.byte $ff,$20
	.word @ref38
	.byte $ff,$10
	.word @ref36
	.byte $ff,$20
	.word @ref38
	.byte $ff,$18
	.word @ref38
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref48:
	.byte $bf
@ref49:
	.byte $bf
@song0ch4loop:
@ref50:
	.byte $f9,$85
@ref51:
	.byte $f9,$85
@ref52:
	.byte $f9,$85
@ref53:
	.byte $bf
@ref54:
	.byte $f9,$85
@ref55:
	.byte $f9,$85
@ref56:
	.byte $f9,$85
@ref57:
	.byte $bf
@ref58:
	.byte $f9,$85
@ref59:
	.byte $df
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref60:
	.byte $8e,$5d,$5d,$5d,$57,$5b,$5b,$5b,$57,$5d,$5d,$5d,$57,$5b,$5b,$5a
	.byte $85,$56,$85,$56,$85,$56,$8d
@ref61:
	.byte $58,$83,$52,$83,$4f,$4c,$83,$4e,$83,$53,$56,$8d,$56,$8d
@ref62:
	.byte $57,$4f,$49,$4f,$65,$5d,$5c,$85,$57,$4f,$49,$4f,$65,$5d,$5c,$85
@ref63:
	.byte $61,$60,$60,$5d,$61,$57,$57,$56,$85,$61,$60,$60,$5d,$61,$57,$57
	.byte $56,$85
@ref64:
	.byte $52,$89,$53,$53,$59,$57,$53,$57,$4e,$99
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$12
	.word @ref63
@ref67:
	.byte $4c,$8d,$52,$8d
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref68:
	.byte $90,$4f,$4f,$4f,$57,$49,$49,$49,$45,$4f,$4f,$4f,$57,$49,$49,$49
	.byte $45,$36,$85,$48,$85,$36,$8d
@ref69:
	.byte $36,$83,$40,$37,$31,$44,$89,$41,$36,$8d,$4e,$8d
@ref70:
	.byte $82,$48,$00,$48,$00,$48,$00,$48,$00,$56,$00,$56,$00,$52,$00,$53
	.byte $48,$00,$48,$00,$48,$00,$48,$00,$56,$00,$56,$00,$52,$00,$52,$81
@ref71:
	.byte $56,$00,$56,$00,$52,$00,$57,$4e,$00,$36,$00,$36,$85,$56,$00,$56
	.byte $00,$52,$00,$57,$4e,$00,$36,$00,$36,$85
@ref72:
	.byte $22,$8d,$1a,$85,$14,$85,$18,$9d
	.byte $ff,$08
	.word @ref72
	.byte $ff,$1a
	.word @ref71
@ref75:
	.byte $0b,$00,$89,$15,$00,$89
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref76:
	.byte $80,$1f,$01,$27,$2d,$00,$89,$15,$1f,$01,$27,$2d,$00,$89,$15,$3e
	.byte $00,$3a,$36,$3e,$00,$3a,$36,$3f,$01,$31,$00,$81
@ref77:
	.byte $29,$00,$30,$37,$01,$2c,$83,$34,$01,$41,$36,$83,$00,$87,$47,$00
	.byte $89
@ref78:
	.byte $8e,$19,$01,$27,$31,$2c,$85,$01,$0f,$19,$01,$27,$31,$2c,$85,$01
	.byte $0e,$81
@ref79:
	.byte $80,$18,$85,$30,$85,$27,$1f,$19,$01,$18,$85,$30,$85,$27,$1f,$19
	.byte $00,$81
@ref80:
	.byte $1a,$83,$00,$23,$32,$85,$00,$89,$18,$83,$00,$27,$31,$18,$83,$00
	.byte $27,$30,$81
	.byte $ff,$13
	.word @ref80
@ref82:
	.byte $18,$85,$30,$85,$27,$1f,$19,$01,$18,$85,$30,$85,$27,$1f,$19,$00
	.byte $81
@ref83:
	.byte $14,$00,$8b,$1c,$00,$8b
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref84:
	.byte $8a,$03,$03,$8c,$15,$88,$0e,$8d,$14,$18,$8a,$03,$03,$8c,$15,$88
	.byte $0e,$8f,$14,$18,$85,$14,$85,$15,$8c,$1f,$1f,$1e,$81
@ref85:
	.byte $8a,$02,$83,$88,$10,$83,$8a,$03,$88,$12,$83,$10,$83,$8a,$21,$20
	.byte $8b,$20,$12,$8d
@ref86:
	.byte $8c,$20,$83,$20,$88,$02,$85,$8c,$21,$21,$88,$02,$85,$8c,$20,$83
	.byte $20,$88,$02,$85,$8c,$21,$21,$88,$02,$85
	.byte $ff,$12
	.word @ref86
	.byte $ff,$12
	.word @ref86
	.byte $ff,$12
	.word @ref86
	.byte $ff,$12
	.word @ref86
	.byte $ff,$09
	.word @ref86
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref92:
	.byte $df
@ref93:
	.byte $bf
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref100:
	.byte $86,$4e,$89,$58,$85,$01,$4e,$85
@ref101:
	.byte $52,$89,$5c,$85,$00,$85,$58,$81
@ref102:
	.byte $56,$00,$56,$00,$56,$00,$56,$00,$56,$00,$56,$00,$52,$00,$56,$00
@ref103:
	.byte $83,$5d,$01,$59,$4f,$01,$53,$00,$81
@ref104:
	.byte $4e,$89,$58,$85,$01,$4e,$85
	.byte $ff,$08
	.word @ref101
	.byte $ff,$10
	.word @ref102
@ref107:
	.byte $83,$5d,$01,$59,$59,$01,$5d,$00,$81
@ref108:
	.byte $8e,$49,$49,$49,$3f,$49,$49,$45,$40,$85,$48,$85,$40,$85,$3a,$85
	.byte $3e,$81
@ref109:
	.byte $83,$48,$85,$39,$3f,$3b,$39,$3a,$85,$30,$99
@ref110:
	.byte $49,$49,$49,$3f,$49,$49,$45,$40,$85,$44,$85,$48,$85,$4a,$89
@ref111:
	.byte $82,$4a,$8d,$8e,$4f,$4b,$41,$44,$85,$00,$8d,$82,$36,$85,$00,$81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref112:
	.byte $92,$30,$89,$36,$89,$30,$85
@ref113:
	.byte $32,$89,$3a,$91
@ref114:
	.byte $36,$9b,$00
@ref115:
	.byte $83,$41,$01,$37,$31,$01,$33,$00,$81
@ref116:
	.byte $30,$89,$36,$89,$30,$85
@ref117:
	.byte $32,$89,$3a,$91
@ref118:
	.byte $36,$9b,$00
@ref119:
	.byte $83,$41,$01,$37,$41,$00,$85,$00,$81
@ref120:
	.byte $30,$89,$38,$89,$30,$85,$3a,$89,$40,$89,$3a,$85
@ref121:
	.byte $30,$89,$3e,$89,$30,$85,$3a,$89,$40,$85,$00,$89
@ref122:
	.byte $30,$89,$3e,$89,$38,$85,$3a,$89,$40,$85,$3a,$89
@ref123:
	.byte $40,$99,$82,$36,$91,$01,$46,$85,$00,$81
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref124:
	.byte $80,$29,$01,$30,$34,$37,$01,$30,$00,$28,$00,$22,$00
@ref125:
	.byte $2d,$00,$38,$3b,$35,$00,$89,$32,$81
@ref126:
	.byte $1f,$01,$27,$2d,$01,$27,$1f,$26,$00
@ref127:
	.byte $83,$2d,$01,$29,$27,$01,$22,$85
@ref128:
	.byte $29,$01,$30,$34,$37,$01,$30,$00,$28,$00,$22,$00
	.byte $ff,$09
	.word @ref125
	.byte $ff,$09
	.word @ref126
@ref131:
	.byte $83,$2d,$01,$28,$00,$29,$01,$82,$37,$00,$81
@ref132:
	.byte $80,$30,$85,$01,$21,$01,$27,$21,$23,$01,$29,$01,$31,$01,$29,$23
	.byte $28,$81
@ref133:
	.byte $26,$85,$01,$30,$85,$01,$21,$01,$3b,$31,$01,$37,$01,$33,$2d,$00
	.byte $81
@ref134:
	.byte $30,$85,$01,$21,$01,$27,$21,$23,$01,$29,$01,$31,$01,$29,$23,$28
	.byte $81
@ref135:
	.byte $1b,$01,$23,$29,$01,$23,$1b,$01,$1f,$01,$27,$2d,$01,$2e,$89
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref136:
	.byte $8a,$02,$85,$88,$19,$8a,$02,$85,$88,$0d,$0d,$0c,$81
@ref137:
	.byte $8a,$02,$85,$88,$19,$8a,$02,$85,$88,$0d,$18,$85
@ref138:
	.byte $8a,$20,$85,$88,$18,$85,$8a,$20,$85,$88,$19,$18,$81
@ref139:
	.byte $83,$18,$85,$0b,$0a,$85,$20,$85
	.byte $ff,$09
	.word @ref136
	.byte $ff,$08
	.word @ref137
	.byte $ff,$09
	.word @ref138
	.byte $ff,$08
	.word @ref139
@ref144:
	.byte $8a,$20,$85,$88,$18,$85,$8a,$20,$85,$88,$19,$8a,$20,$85,$88,$18
	.byte $85,$18,$85,$19,$18,$85
	.byte $ff,$10
	.word @ref144
	.byte $ff,$10
	.word @ref144
	.byte $ff,$10
	.word @ref144
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref148:
	.byte $9f
@ref149:
	.byte $9f
@ref150:
	.byte $9f
@ref151:
	.byte $9f
@ref152:
	.byte $9f
@ref153:
	.byte $9f
@ref154:
	.byte $9f
@ref155:
	.byte $9f
@ref156:
	.byte $bf
@ref157:
	.byte $bf
@ref158:
	.byte $bf
@ref159:
	.byte $bf
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref160:
	.byte $8e,$52,$85,$52,$85,$52,$85,$55,$58,$85,$62,$87,$00,$8f
@ref161:
	.byte $52,$85,$52,$85,$52,$85,$4f,$52,$a1
@ref162:
	.byte $52,$85,$52,$85,$52,$85,$55,$58,$85,$62,$89,$62,$85,$66,$85
@ref163:
	.byte $6a,$8d,$6a,$85,$67,$62,$a1
@ref164:
	.byte $5d,$5d,$5d,$5d,$62,$85,$62,$8d,$82,$67,$01,$62,$85,$00,$85
@ref165:
	.byte $8e,$59,$59,$59,$59,$62,$85,$62,$8d,$82,$67,$01,$62,$85,$00,$85
@ref166:
	.byte $8e,$4f,$4f,$4f,$4f,$54,$85,$54,$8d,$5c,$85,$59,$59,$54,$85
@ref167:
	.byte $52,$85,$55,$58,$91,$82,$63,$01,$61,$01,$5c,$85,$59,$00,$81
@ref168:
	.byte $8e,$5d,$5d,$5d,$5d,$62,$85,$62,$8d,$82,$67,$01,$62,$85,$00,$85
	.byte $ff,$0e
	.word @ref165
	.byte $ff,$0e
	.word @ref166
@ref171:
	.byte $52,$85,$62,$95,$82,$33,$3d,$45,$4b,$49,$41,$37,$00,$81
@ref172:
	.byte $8e,$6a,$85,$66,$85,$62,$85,$6b,$66,$85,$60,$89,$6a,$85,$66,$85
@ref173:
	.byte $62,$85,$61,$5c,$85,$62,$95,$5d,$61,$5d,$61,$58,$81
@ref174:
	.byte $ab,$59,$5d,$59,$5d,$54,$81
@ref175:
	.byte $ab,$55,$59,$55,$58,$85
@ref176:
	.byte $52,$85,$62,$95
@ref177:
	.byte $82,$33,$3d,$45,$4b,$49,$41,$37,$00,$81
	.byte $ff,$0f
	.word @ref172
@ref179:
	.byte $62,$85,$61,$5c,$85,$62,$95,$5d,$61,$5d,$60,$85
@ref180:
	.byte $58,$85,$62,$95
@ref181:
	.byte $8b,$5d,$61,$5d,$60,$85
@ref182:
	.byte $62,$85,$62,$95
	.byte $ff,$09
	.word @ref177
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@song3ch1loop:
@ref184:
	.byte $92,$41,$01,$41,$01,$41,$01,$4b,$53,$01,$4b,$00,$95
@ref185:
	.byte $41,$01,$41,$01,$41,$01,$45,$40,$00,$97,$84,$4b,$00,$81
	.byte $ff,$0c
	.word @ref184
	.byte $ff,$0d
	.word @ref185
@ref188:
	.byte $54,$85,$01,$55,$3d,$54,$85,$01,$54,$85,$01,$3d,$54,$85,$00,$85
@ref189:
	.byte $4a,$85,$01,$4b,$33,$4a,$85,$01,$4a,$85,$01,$33,$4a,$85,$00,$85
@ref190:
	.byte $98,$4e,$85,$01,$4f,$37,$4e,$85,$01,$9a,$58,$85,$01,$41,$58,$85
	.byte $00,$85
@ref191:
	.byte $84,$4a,$85,$01,$4b,$33,$4a,$85,$01,$4a,$85,$01,$33,$4a,$85,$00
	.byte $85
	.byte $ff,$10
	.word @ref188
	.byte $ff,$10
	.word @ref189
	.byte $ff,$10
	.word @ref190
@ref195:
	.byte $84,$4a,$85,$01,$4b,$33,$4a,$85,$01,$98,$4f,$01,$4f,$37,$9a,$59
	.byte $41,$59,$00,$81
@ref196:
	.byte $84,$32,$85,$01,$4b,$32,$85,$01,$96,$3a,$00,$3a,$85,$01,$53,$3a
	.byte $85,$01,$52,$81
@ref197:
	.byte $98,$44,$85,$01,$5d,$44,$85,$01,$5d,$84,$3c,$85,$01,$55,$3c,$85
	.byte $01,$4a,$81
@ref198:
	.byte $4a,$85,$01,$4b,$33,$4a,$85,$01,$4a,$85,$01,$4b,$33,$4a,$85,$00
	.byte $81
	.byte $ff,$10
	.word @ref190
@ref200:
	.byte $84,$4a,$85,$01,$4b,$33,$4a,$85,$00,$81
@ref201:
	.byte $98,$4f,$01,$4f,$37,$9a,$59,$41,$59,$00,$81
	.byte $ff,$12
	.word @ref196
	.byte $ff,$11
	.word @ref197
@ref204:
	.byte $4a,$85,$01,$4b,$33,$4a,$85,$00,$81
	.byte $ff,$09
	.word @ref201
	.byte $ff,$09
	.word @ref200
	.byte $ff,$09
	.word @ref201
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@song3ch2loop:
@ref208:
	.byte $80,$1a,$85,$01,$1a,$00,$1a,$85,$01,$29,$1a,$85,$01,$1a,$00,$1b
	.byte $33,$29,$22,$81
@ref209:
	.byte $1a,$85,$01,$1a,$00,$1a,$85,$01,$29,$1a,$85,$01,$1a,$00,$1a,$85
	.byte $28,$22,$1a,$81
@ref210:
	.byte $1a,$85,$01,$1a,$00,$1a,$85,$01,$29,$1a,$85,$01,$1a,$00,$1b,$33
	.byte $29,$22,$81
	.byte $ff,$14
	.word @ref209
@ref212:
	.byte $24,$85,$01,$1b,$25,$2d,$25,$00,$89,$1b,$01,$24,$85,$00,$85
@ref213:
	.byte $22,$85,$01,$1b,$23,$29,$22,$85,$00,$85,$1b,$01,$22,$85,$00,$85
@ref214:
	.byte $1e,$85,$01,$25,$2d,$32,$85,$01,$1e,$85,$01,$25,$29,$31,$00,$85
@ref215:
	.byte $1a,$85,$01,$23,$1b,$10,$85,$01,$23,$01,$29,$01,$33,$01,$28,$85
	.byte $ff,$0f
	.word @ref212
	.byte $ff,$10
	.word @ref213
	.byte $ff,$10
	.word @ref214
@ref219:
	.byte $1a,$85,$01,$23,$1b,$10,$85,$01,$82,$24,$00,$24,$00,$24,$00,$24
	.byte $00,$28,$00,$28,$00,$28,$2c,$30,$32
@ref220:
	.byte $80,$1a,$85,$01,$1a,$00,$1a,$85,$01,$18,$00,$18,$85,$01,$18,$00
	.byte $18,$85,$01,$18,$00
@ref221:
	.byte $14,$85,$01,$14,$00,$14,$85,$01,$14,$00,$14,$85,$01,$1b,$24,$85
	.byte $01,$1a,$81
@ref222:
	.byte $1a,$85,$01,$23,$1b,$10,$85,$01,$1a,$85,$01,$23,$1b,$10,$85,$00
	.byte $81
	.byte $ff,$10
	.word @ref214
@ref224:
	.byte $1a,$85,$01,$23,$1b,$10,$85,$00,$81
@ref225:
	.byte $82,$24,$00,$24,$00,$24,$00,$24,$00,$28,$00,$28,$00,$28,$2c,$30
	.byte $32
	.byte $ff,$14
	.word @ref220
	.byte $ff,$13
	.word @ref221
	.byte $ff,$09
	.word @ref224
@ref229:
	.byte $24,$85,$01,$1f,$28,$89,$00,$81
	.byte $ff,$09
	.word @ref224
	.byte $ff,$10
	.word @ref225
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@song3ch3loop:
@ref232:
	.byte $8a,$20,$85,$88,$13,$8a,$21,$20,$85,$88,$12,$85,$8a,$20,$85,$88
	.byte $13,$8a,$21,$20,$85,$88,$13,$12,$81
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$08
	.word @ref232
@ref249:
	.byte $8a,$20,$85,$88,$13,$8a,$21,$20,$85,$88,$13,$12,$81
	.byte $ff,$11
	.word @ref232
	.byte $ff,$11
	.word @ref232
	.byte $ff,$08
	.word @ref232
	.byte $ff,$09
	.word @ref249
	.byte $ff,$08
	.word @ref232
	.byte $ff,$09
	.word @ref249
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@song3ch4loop:
@ref256:
	.byte $bf
@ref257:
	.byte $bf
@ref258:
	.byte $bf
@ref259:
	.byte $bf
@ref260:
	.byte $bf
@ref261:
	.byte $bf
@ref262:
	.byte $bf
@ref263:
	.byte $bf
@ref264:
	.byte $bf
@ref265:
	.byte $bf
@ref266:
	.byte $bf
@ref267:
	.byte $bf
@ref268:
	.byte $bf
@ref269:
	.byte $bf
@ref270:
	.byte $bf
@ref271:
	.byte $bf
@ref272:
	.byte $9f
@ref273:
	.byte $9f
@ref274:
	.byte $bf
@ref275:
	.byte $bf
@ref276:
	.byte $9f
@ref277:
	.byte $9f
@ref278:
	.byte $9f
@ref279:
	.byte $9f
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$06
@song4ch0loop:
@ref280:
	.byte $90,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b
	.byte $62,$81
@ref281:
	.byte $5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b,$62
	.byte $81
@ref282:
	.byte $a2,$2c,$9d,$2a,$9d
@ref283:
	.byte $28,$9d,$2a,$9d
@ref284:
	.byte $44,$9d,$48,$9d
@ref285:
	.byte $4a,$9d,$4e,$9d
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref286:
	.byte $a4,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b,$63,$5d,$63,$5b
	.byte $62,$81
	.byte $ff,$11
	.word @ref281
@ref288:
	.byte $44,$9d,$42,$9d
@ref289:
	.byte $40,$9d,$42,$9d
@ref290:
	.byte $5c,$9d,$60,$9d
@ref291:
	.byte $62,$9d,$66,$9d
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref292:
	.byte $9c,$15,$1b,$1b,$15,$1b,$1b,$15,$1b,$15,$1b,$1b,$15,$1b,$1b,$15
	.byte $1a,$81
@ref293:
	.byte $13,$1b,$1b,$13,$1b,$1b,$13,$1b,$13,$1b,$1b,$13,$1b,$1b,$13,$1a
	.byte $81
@ref294:
	.byte $2d,$33,$2d,$33,$2d,$33,$2d,$33,$2b,$33,$2b,$33,$2b,$33,$2b,$32
	.byte $81
@ref295:
	.byte $29,$33,$29,$33,$29,$33,$29,$33,$2b,$33,$2b,$33,$2b,$33,$2b,$32
	.byte $81
	.byte $ff,$11
	.word @ref294
	.byte $ff,$11
	.word @ref295
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref298:
	.byte $9e,$20,$20,$21,$21,$20,$20,$21,$21,$21,$21,$20,$20,$21,$21,$20
	.byte $20,$21,$21,$21,$20,$81
@ref299:
	.byte $20,$20,$21,$21,$20,$20,$21,$21,$21,$21,$20,$20,$21,$21,$20,$20
	.byte $21,$21,$20,$20,$20,$20
@ref300:
	.byte $a0,$21,$21,$9e,$20,$89,$a0,$21,$9e,$20,$85,$a0,$21,$21,$9e,$20
	.byte $89,$a0,$21,$9e,$20,$85
	.byte $ff,$0e
	.word @ref300
	.byte $ff,$0e
	.word @ref300
	.byte $ff,$0e
	.word @ref300
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref304:
	.byte $bf
@ref305:
	.byte $bf
@ref306:
	.byte $bf
@ref307:
	.byte $bf
@ref308:
	.byte $bf
@ref309:
	.byte $bf
	.byte $fd
	.word @song4ch4loop
