// Tileset tilemaps & pals generated by mkts [nes mode]
// Copyleft 2015 The Mojon Twins
 
const unsigned char tstitle_pals [] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2
};

const unsigned char tstitle_tmaps [] = {
	133, 133, 133, 133, 
	134, 135, 136, 137, 
	138, 139, 140, 141, 
	142, 143, 144, 145, 
	146, 133, 147, 148, 
	133, 149, 150, 151, 
	152, 153, 154, 155, 
	156, 157, 158, 159, 
	160, 161, 162, 163, 
	164, 164, 165, 165, 
	166, 133, 133, 167, 
	168, 133, 133, 133
};
