// Tileset tilemaps & pals generated by mkts
// Copyleft 2015 The Mojon Twins
 
const unsigned char tstitle_pals [] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2
};

const unsigned char tstitle_tmaps [] = {
	133, 133, 133, 133, 
	134, 135, 136, 137, 
	138, 139, 140, 141, 
	142, 143, 144, 145, 
	146, 147, 148, 149, 
	150, 139, 151, 152, 
	142, 143, 144, 145, 
	146, 147, 148, 153, 
	154, 155, 156, 157, 
	158, 158, 159, 159, 
	160, 133, 133, 161, 
	162, 133, 133, 133
};
