// Tileset tilemaps & pals generated by mkts [nes mode]
// Copyleft 2015 The Mojon Twins
 
const unsigned char tstitle_pals [] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

const unsigned char tstitle_tmaps [] = {
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133, 
	133, 133, 133, 133
};
