// RLEPacked(TM) map ..\dev\assets\map0.h
// Generated by rlemap2.exe
// Copyleft 2015, 2017 The Mojon Twins

// Map Size Is 5x5
// Screen Size Is 16x12

// Compressed map structure, screens
// Format: [SCR_SIZE, [ T COUNT | 0xF0 + COUNT T1 T2 T3 T4 ... ] | 0, 96 packed bytes]

// scr_0_00 is empty.
// scr_0_01 is empty.
// scr_0_02 is empty.
// scr_0_03 is empty.
// scr_0_04 is empty.
// scr_0_05 is empty.
// scr_0_06 is empty.
// scr_0_07 is empty.
// scr_0_08 is empty.
// scr_0_09 is empty.
// scr_0_0a is empty.
// scr_0_0b is empty.
// scr_0_0c is empty.
// scr_0_0d is empty.
// scr_0_0e is empty.
// scr_0_0f is empty.
// scr_0_10 is empty.
// scr_0_11 is empty.
// scr_0_12 is empty.
// scr_0_13 is empty.
// scr_0_14 is empty.
// scr_0_15 is empty.
// scr_0_16 is empty.
// scr_0_17 is empty.
// scr_0_18 is empty.

// Compressed map array

const unsigned char * const map_0 [] = {
	0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0
};

// Total map size in bytes is 50

#define N_BOLTS_0 0
