;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 3
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env19
	.byte $00
	.byte $30 ;instrument $04
	.word @env4,@env15,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env13,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env12,@env0,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env14,@env0,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env4,@env15,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env8,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $0e
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env11,@env18,@env0
	.byte $00
	.byte $30 ;instrument $11
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env9,@env0,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env4,@env15,@env0
	.byte $00
	.byte $b0 ;instrument $14
	.word @env10,@env0,@env0
	.byte $00
	.byte $70 ;instrument $15
	.word @env7,@env16,@env0
	.byte $00
	.byte $30 ;instrument $16
	.word @env11,@env17,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c1,$c2,$c3,$c6,$00,$03
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $cc,$00,$00
@env4:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env5:
	.byte $cf,$cc,$c9,$c7,$c5,$c4,$c3,$c3,$c2,$03,$c8,$c6,$c4,$c3,$c3,$c2
	.byte $02,$c1,$03,$c4,$c3,$c2,$04,$c1,$04,$c3,$c2,$c1,$07,$c0,$00,$1d
@env6:
	.byte $c4,$c3,$c3,$c2,$03,$c1,$04,$c3,$c2,$c2,$c1,$08,$c2,$c2,$c1,$0a
	.byte $c2,$c1,$07,$c0,$00,$13
@env7:
	.byte $cf,$ce,$cd,$cc,$cb,$ca,$c9,$c1,$00,$07
@env8:
	.byte $cd,$cc,$ca,$c9,$c7,$c6,$c5,$c3,$c0,$00,$08
@env9:
	.byte $cb,$ca,$c8,$c7,$c5,$c4,$c3,$c1,$c0,$00,$08
@env10:
	.byte $c1,$c3,$c4,$c6,$c7,$c8,$c9,$ca,$ca,$cb,$cc,$cc,$cd,$0d,$cc,$cc
	.byte $cb,$ca,$c7,$c1,$00,$13
@env11:
	.byte $ce,$ce,$cd,$02,$cc,$04,$cb,$04,$ca,$03,$c9,$05,$c8,$06,$c7,$04
	.byte $c6,$06,$c5,$09,$c4,$08,$c3,$0c,$c2,$14,$c1,$1d,$c1,$00,$1c
@env12:
	.byte $cf,$cd,$cb,$c9,$c7,$c6,$c5,$c4,$c3,$06,$c3,$00,$0a
@env13:
	.byte $ca,$c5,$c3,$c2,$c0,$00,$04
@env14:
	.byte $cf,$cf,$ce,$ce,$cd,$cb,$c6,$c5,$c3,$c3,$c2,$c2,$c1,$02,$c1,$00
	.byte $0e
@env15:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env16:
	.byte $cc,$c0,$00,$01
@env17:
	.byte $c0,$03,$c3,$03,$c7,$03,$c3,$02,$c3,$00,$00
@env18:
	.byte $c0,$03,$c4,$03,$c7,$03,$c4,$02,$c4,$00,$00
@env19:
	.byte $c0,$0b,$c1,$c2,$c3,$c4,$c3,$c2,$c1,$c0,$00,$02


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $00,$ed,$94,$5c,$8d
@ref1:
	.byte $6a,$a5,$67,$63,$60,$85,$5c,$bd,$5c,$85
@ref2:
	.byte $6a,$a5,$67,$63,$60,$85,$62,$b5,$6a,$8d
@ref3:
	.byte $62,$a5,$60,$85,$5c,$85,$60,$85,$5c,$ad,$6a,$8d
@ref4:
	.byte $5c,$ad,$74,$8d,$6a,$bd
@ref5:
	.byte $66,$ad,$6a,$85,$6c,$85,$62,$bd
@ref6:
	.byte $66,$ad,$6a,$85,$6c,$85,$6a,$bd
@ref7:
	.byte $66,$9d,$6c,$8d,$66,$8d,$6a,$85,$66,$85,$62,$85,$58,$85,$70,$85
	.byte $58,$85,$6c,$85,$70,$85
@ref8:
	.byte $6a,$ad,$6a,$8d,$74,$ad,$5c,$8d
	.byte $ff,$0a
	.word @ref1
	.byte $ff,$0a
	.word @ref2
	.byte $ff,$0c
	.word @ref3
	.byte $ff,$06
	.word @ref4
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref13:
	.byte $00,$f9,$83
@ref14:
	.byte $00,$85,$96,$5c,$8d,$6a,$a5,$67,$63,$60,$85,$5c,$ad
@ref15:
	.byte $87,$5c,$85,$6a,$ad,$67,$63,$60,$85,$62,$ad
@ref16:
	.byte $87,$6a,$8d,$62,$a5,$60,$85,$5c,$85,$60,$85,$5c,$a5
@ref17:
	.byte $87,$6a,$8d,$5c,$ad,$74,$8d,$6a,$a5
@ref18:
	.byte $87,$6c,$b5,$58,$85,$6a,$85,$6c,$85,$62,$a5
@ref19:
	.byte $87,$6c,$b5,$62,$85,$6a,$85,$6c,$85,$6a,$a5
@ref20:
	.byte $8f,$5c,$85,$66,$9d,$6c,$8d,$66,$8d,$6a,$85,$66,$85,$62,$85,$5c
	.byte $85,$70,$85
@ref21:
	.byte $58,$85,$6c,$85,$70,$85,$6a,$ad,$6a,$8d,$74,$a5
@ref22:
	.byte $00,$85,$5c,$8d,$6a,$a5,$67,$63,$60,$85,$5c,$ad
	.byte $ff,$0b
	.word @ref15
	.byte $ff,$0d
	.word @ref16
	.byte $ff,$09
	.word @ref17
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref26:
	.byte $8e,$14,$8d,$00,$85,$15,$01,$14,$8d,$00,$8d,$14,$8d,$00,$85,$15
	.byte $01,$14,$8d,$00,$8d
@ref27:
	.byte $14,$8d,$00,$85,$15,$01,$14,$8d,$00,$8d,$14,$8d,$00,$85,$15,$01
	.byte $14,$8d,$00,$8d
@ref28:
	.byte $14,$8d,$00,$85,$15,$01,$14,$8d,$00,$8d,$1a,$8d,$00,$85,$1b,$01
	.byte $1a,$8d,$00,$8d
@ref29:
	.byte $1a,$8d,$00,$85,$1b,$01,$1a,$8d,$00,$8d,$14,$8d,$00,$85,$15,$01
	.byte $14,$8d,$00,$8d
	.byte $ff,$14
	.word @ref27
@ref31:
	.byte $1e,$8d,$00,$85,$1f,$01,$1e,$8d,$00,$8d,$1a,$8d,$00,$85,$1b,$01
	.byte $1a,$8d,$00,$8d
	.byte $ff,$14
	.word @ref31
	.byte $ff,$14
	.word @ref31
	.byte $ff,$14
	.word @ref27
	.byte $ff,$14
	.word @ref27
	.byte $ff,$14
	.word @ref28
	.byte $ff,$14
	.word @ref29
	.byte $ff,$14
	.word @ref27
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref39:
	.byte $92,$20,$8d,$90,$20,$8d,$92,$20,$8d,$90,$20,$8d,$92,$20,$8d,$90
	.byte $20,$8d,$92,$20,$8d,$90,$20,$8d
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $ff,$10
	.word @ref39
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref52:
	.byte $f9,$85
@ref53:
	.byte $f9,$85
@ref54:
	.byte $f9,$85
@ref55:
	.byte $f9,$85
@ref56:
	.byte $f9,$85
@ref57:
	.byte $f9,$85
@ref58:
	.byte $f9,$85
@ref59:
	.byte $f9,$85
@ref60:
	.byte $f9,$85
@ref61:
	.byte $f9,$85
@ref62:
	.byte $f9,$85
@ref63:
	.byte $f9,$85
@ref64:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@ref65:
	.byte $00,$f9,$83
@song1ch0loop:
@ref66:
	.byte $00,$f9,$83
@ref67:
	.byte $a4,$3a,$f9,$83
@ref68:
	.byte $3a,$f9,$83
@ref69:
	.byte $98,$3c,$f9,$83
@ref70:
	.byte $a4,$3a,$f9,$83
@ref71:
	.byte $3a,$f9,$83
@ref72:
	.byte $3a,$f9,$83
@ref73:
	.byte $98,$3c,$f9,$83
@ref74:
	.byte $a4,$3a,$f9,$83
@ref75:
	.byte $3a,$f9,$83
@ref76:
	.byte $3a,$f9,$83
@ref77:
	.byte $3a,$f9,$83
@ref78:
	.byte $3a,$f9,$83
@ref79:
	.byte $00,$f9,$83
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@ref80:
	.byte $00,$f9,$83
@song1ch1loop:
@ref81:
	.byte $00,$f9,$83
@ref82:
	.byte $a2,$3a,$b1,$45,$41,$3d,$3a,$bd
@ref83:
	.byte $3a,$b1,$45,$41,$3d,$3a,$bd
@ref84:
	.byte $3c,$ad,$44,$85,$45,$47,$44,$8d,$40,$8d,$3c,$8d,$36,$8d
@ref85:
	.byte $3a,$b1,$37,$33,$37,$3a,$9d,$22,$9d
@ref86:
	.byte $3a,$ad,$45,$45,$41,$3d,$3a,$bd
	.byte $ff,$08
	.word @ref86
	.byte $ff,$0e
	.word @ref84
	.byte $ff,$09
	.word @ref85
@ref90:
	.byte $a0,$48,$8d,$00,$85,$49,$45,$48,$85,$4a,$85,$4e,$85,$40,$85,$52
	.byte $8d,$4e,$85,$4a,$95,$48,$85,$44,$85
@ref91:
	.byte $48,$8d,$00,$85,$49,$45,$48,$85,$44,$85,$40,$85,$3a,$85,$3e,$8d
	.byte $40,$85,$44,$8d,$48,$85,$4a,$8d
@ref92:
	.byte $48,$8d,$00,$85,$49,$45,$48,$85,$4a,$85,$4e,$85,$40,$85,$52,$8d
	.byte $4e,$85,$4a,$95,$48,$85,$44,$85
@ref93:
	.byte $48,$89,$00,$89,$49,$45,$48,$85,$44,$85,$40,$85,$3a,$85,$3e,$8d
	.byte $40,$85,$3e,$8d,$00,$85,$40,$85,$3e,$85
@ref94:
	.byte $3a,$8d,$00,$ed
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@ref95:
	.byte $9a,$22,$89,$23,$2c,$85,$24,$85,$22,$89,$23,$2c,$85,$29,$25,$22
	.byte $89,$23,$2c,$85,$24,$85,$22,$89,$23,$2c,$85,$29,$24,$81
@song1ch2loop:
	.byte $ff,$1d
	.word @ref95
@ref97:
	.byte $22,$89,$23,$2c,$85,$24,$85,$22,$89,$23,$2c,$85,$29,$25,$22,$89
	.byte $23,$2c,$85,$24,$85,$22,$89,$23,$2c,$85,$29,$24,$81
	.byte $ff,$1d
	.word @ref97
@ref99:
	.byte $24,$89,$25,$32,$85,$2c,$85,$24,$89,$25,$32,$85,$31,$2d,$24,$89
	.byte $25,$32,$85,$2c,$85,$24,$89,$25,$32,$85,$31,$2c,$81
	.byte $ff,$1d
	.word @ref97
	.byte $ff,$1d
	.word @ref97
	.byte $ff,$1d
	.word @ref97
	.byte $ff,$1d
	.word @ref99
	.byte $ff,$1d
	.word @ref97
	.byte $ff,$1d
	.word @ref97
	.byte $ff,$1d
	.word @ref97
	.byte $ff,$1d
	.word @ref97
	.byte $ff,$1d
	.word @ref97
	.byte $ff,$1d
	.word @ref97
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@ref110:
	.byte $9c,$20,$8d,$9e,$20,$8d,$9c,$21,$20,$85,$21,$9e,$20,$85,$20,$85
	.byte $9c,$20,$8d,$9e,$20,$8d,$9c,$21,$20,$85,$21,$9e,$20,$85,$20,$85
@song1ch3loop:
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $ff,$18
	.word @ref110
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@ref125:
	.byte $f9,$85
@song1ch4loop:
@ref126:
	.byte $f9,$85
@ref127:
	.byte $f9,$85
@ref128:
	.byte $f9,$85
@ref129:
	.byte $f9,$85
@ref130:
	.byte $f9,$85
@ref131:
	.byte $f9,$85
@ref132:
	.byte $f9,$85
@ref133:
	.byte $f9,$85
@ref134:
	.byte $f9,$85
@ref135:
	.byte $f9,$85
@ref136:
	.byte $f9,$85
@ref137:
	.byte $f9,$85
@ref138:
	.byte $f9,$85
@ref139:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$0d
@song2ch0loop:
@ref140:
	.byte $8a,$2c,$9d,$2c,$9d
@ref141:
	.byte $44,$9d,$44,$9d
@ref142:
	.byte $2c,$9d,$2c,$9d
@ref143:
	.byte $2c,$9d,$2c,$9d
@ref144:
	.byte $2c,$8d,$2c,$8d,$2c,$8d,$2c,$8d,$2c,$8d
@ref145:
	.byte $2c,$8d,$26,$9d,$2a,$89,$2d,$2a,$85,$26,$85
@ref146:
	.byte $2c,$9d,$2c,$8d,$2c,$85,$2e,$85
@ref147:
	.byte $32,$8d,$1a,$8d,$32,$8d,$1a,$8d
@ref148:
	.byte $32,$85,$24,$85,$3c,$85,$24,$85,$40,$85,$33,$3d,$36,$8d
@ref149:
	.byte $8f,$2c,$8d,$3a,$8d,$3c,$8d
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref150:
	.byte $00,$bd
@ref151:
	.byte $bf
@ref152:
	.byte $8a,$3a,$85,$37,$3b,$3d,$3a,$89,$00,$9d
@ref153:
	.byte $3a,$85,$45,$3d,$41,$3d,$3a,$85,$00,$9d
@ref154:
	.byte $4e,$85,$4c,$95,$4e,$85,$4c,$95,$52,$85,$4e,$85
@ref155:
	.byte $4c,$85,$48,$85,$4e,$9d,$52,$9d
@ref156:
	.byte $44,$91,$3b,$3d,$37,$44,$8b,$46,$44,$8d
@ref157:
	.byte $3a,$9d,$3a,$9d
@ref158:
	.byte $82,$3d,$25,$2d,$25,$3d,$25,$2d,$25,$00,$89,$8a,$24,$91
@ref159:
	.byte $82,$2c,$85,$3c,$85,$3a,$85,$36,$85,$3c,$85,$40,$85,$3c,$85,$3a
	.byte $85
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref160:
	.byte $80,$44,$9d,$2c,$9d
@ref161:
	.byte $2c,$9d,$2c,$83,$00,$22,$83,$00,$24,$83,$00,$1e,$83,$00
@ref162:
	.byte $2c,$bd
@ref163:
	.byte $22,$85,$1f,$23,$25,$28,$85,$25,$22,$9d
@ref164:
	.byte $2c,$8d,$2c,$2e,$2c,$2e,$2c,$2e,$2c,$2e,$2c,$8d,$2c,$2e,$2c,$2e
	.byte $2c,$2e,$2c,$2e,$2c,$85,$2e,$85
@ref165:
	.byte $28,$85,$1e,$85,$36,$9d,$22,$9d
@ref166:
	.byte $2c,$8d,$3a,$85,$3c,$85,$2c,$8d,$40,$85,$3c,$85
@ref167:
	.byte $22,$9d,$32,$83,$00,$2e,$83,$00,$28,$83,$00,$22,$83,$00
@ref168:
	.byte $32,$9d,$28,$85,$24,$85,$1e,$8d
@ref169:
	.byte $2c,$bd
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref170:
	.byte $86,$21,$88,$1f,$84,$09,$88,$1e,$1e,$86,$20,$88,$1e,$86,$21,$84
	.byte $09,$88,$1e,$1e,$86,$21,$88,$1f,$84,$09,$88,$1e,$1e,$86,$20,$88
	.byte $1e,$86,$21,$84,$09,$88,$1e,$1e
	.byte $ff,$16
	.word @ref170
	.byte $ff,$16
	.word @ref170
	.byte $ff,$16
	.word @ref170
@ref174:
	.byte $8c,$14,$85,$15,$86,$21,$84,$1e,$1e,$86,$20,$88,$1e,$86,$20,$88
	.byte $1e,$86,$20,$88,$1e,$8c,$14,$85,$15,$86,$21,$84,$1e,$1e,$86,$20
	.byte $88,$1e,$86,$20,$88,$1e,$86,$20,$88,$1e,$8c,$14,$85,$14,$85
@ref175:
	.byte $14,$85,$14,$85,$86,$21,$88,$1f,$84,$09,$88,$1e,$1e,$86,$20,$88
	.byte $1e,$86,$21,$84,$09,$88,$1e,$1e,$8c,$15,$88,$1f,$84,$09,$88,$1e
	.byte $1e,$86,$20,$88,$1e,$86,$21,$84,$09,$88,$1e,$1e
	.byte $ff,$16
	.word @ref170
	.byte $ff,$16
	.word @ref170
	.byte $ff,$16
	.word @ref170
	.byte $ff,$16
	.word @ref170
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref180:
	.byte $bf
@ref181:
	.byte $bf
@ref182:
	.byte $bf
@ref183:
	.byte $bf
@ref184:
	.byte $cf
@ref185:
	.byte $cf
@ref186:
	.byte $bf
@ref187:
	.byte $bf
@ref188:
	.byte $bf
@ref189:
	.byte $bf
	.byte $fd
	.word @song2ch4loop
