;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env11
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $70 ;instrument $02
	.word @env3,@env6,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env3,@env6,@env10
	.byte $00
	.byte $30 ;instrument $04
	.word @env1,@env7,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env3,@env8,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env3,@env8,@env10
	.byte $00
	.byte $30 ;instrument $08
	.word @env5,@env9,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c7,$c5,$c4,$c3,$c3,$c2,$06,$c1,$0a,$c0,$00,$09
@env3:
	.byte $c6,$c6,$c5,$c4,$c3,$09,$c2,$08,$c1,$0f,$c0,$00,$0a
@env4:
	.byte $c8,$c3,$c2,$c1,$02,$c0,$00,$05
@env5:
	.byte $c5,$c5,$c4,$c4,$c3,$c0,$00,$05
@env6:
	.byte $c0,$c0,$c5,$c5,$c7,$c7,$00,$00
@env7:
	.byte $c6,$c3,$c0,$00,$02
@env8:
	.byte $c0,$02,$c4,$02,$c7,$c7,$c7,$00,$00
@env9:
	.byte $c6,$c6,$c0,$00,$02
@env10:
	.byte $c4,$00,$00
@env11:
	.byte $c0,$0b,$c1,$c2,$c3,$c4,$c3,$c2,$c1,$c0,$00,$02


@song0ch0:
	.byte $fb,$04
@song0ch0loop:
@ref0:
	.byte $9f
@ref1:
	.byte $9f
@ref2:
	.byte $9f
@ref3:
	.byte $9f
@ref4:
	.byte $9f
@ref5:
	.byte $9f
@ref6:
	.byte $9f
@ref7:
	.byte $9f
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref8:
	.byte $9f
@ref9:
	.byte $9f
@ref10:
	.byte $9f
@ref11:
	.byte $9f
@ref12:
	.byte $9f
@ref13:
	.byte $9f
@ref14:
	.byte $9f
@ref15:
	.byte $9f
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref16:
	.byte $80,$28,$00,$83,$28,$00,$27,$90,$32,$00,$8b
@ref17:
	.byte $80,$24,$00,$83,$25,$23,$90,$32,$00,$8b
@ref18:
	.byte $80,$28,$00,$83,$82,$28,$00,$27,$90,$32,$00,$83,$80,$26,$00,$83
@ref19:
	.byte $24,$00,$83,$25,$90,$32,$80,$22,$83,$00,$89
@ref20:
	.byte $28,$00,$83,$28,$00,$27,$90,$32,$00,$83,$80,$26,$00,$83
@ref21:
	.byte $24,$00,$83,$25,$23,$90,$32,$00,$8b
@ref22:
	.byte $80,$1e,$00,$83,$1e,$00,$23,$90,$32,$00,$83,$80,$25,$90,$32,$80
	.byte $28
@ref23:
	.byte $87,$00,$95
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref24:
	.byte $8a,$1f,$1f,$82,$1f,$8a,$1f,$90,$16,$85,$82,$1f,$8a,$1e,$81
@ref25:
	.byte $83,$1f,$82,$1f,$8a,$1f,$90,$16,$85,$8a,$1e,$85
@ref26:
	.byte $1f,$1f,$82,$1f,$8a,$1f,$90,$16,$85,$82,$1f,$8a,$1e,$81
@ref27:
	.byte $83,$1f,$82,$1f,$90,$16,$89,$8a,$1f,$1e,$81
	.byte $ff,$09
	.word @ref26
	.byte $ff,$08
	.word @ref25
@ref30:
	.byte $1f,$1f,$82,$1f,$8a,$1f,$90,$16,$85,$17,$16,$81
@ref31:
	.byte $87,$8a,$1f,$1f,$82,$1e,$85,$8a,$1f,$1e,$81
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref32:
	.byte $9f
@ref33:
	.byte $9f
@ref34:
	.byte $9f
@ref35:
	.byte $9f
@ref36:
	.byte $9f
@ref37:
	.byte $9f
@ref38:
	.byte $9f
@ref39:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$04
@song1ch0loop:
@ref40:
	.byte $84,$28,$8d,$8c,$40,$89,$40,$89,$40,$8d,$84,$28,$85
@ref41:
	.byte $24,$8d,$8c,$3c,$89,$3c,$89,$3c,$8d,$84,$24,$85
@ref42:
	.byte $28,$8d,$8c,$40,$89,$40,$89,$40,$8d,$84,$28,$85
@ref43:
	.byte $1a,$8d,$8c,$32,$89,$36,$89,$36,$95
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref44:
	.byte $86,$28,$8d,$8e,$40,$89,$40,$89,$40,$8d,$86,$28,$85
@ref45:
	.byte $24,$8d,$8e,$3c,$89,$3c,$89,$3c,$8d,$86,$24,$85
@ref46:
	.byte $28,$8d,$8e,$40,$89,$40,$89,$40,$8d,$86,$28,$85
@ref47:
	.byte $1a,$8d,$8e,$32,$89,$36,$89,$36,$95
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref48:
	.byte $80,$28,$87,$00,$26,$00,$88,$29,$00,$85,$80,$29,$01,$29,$01,$26
	.byte $00,$88,$29,$01,$80,$29,$22,$81
@ref49:
	.byte $24,$87,$00,$22,$00,$88,$25,$00,$85,$80,$25,$01,$25,$01,$22,$00
	.byte $25,$01,$25,$22,$81
@ref50:
	.byte $28,$87,$00,$26,$00,$88,$29,$00,$85,$80,$29,$01,$29,$01,$26,$00
	.byte $88,$29,$01,$80,$29,$00,$81
@ref51:
	.byte $32,$87,$00,$30,$00,$33,$00,$85,$37,$01,$37,$01,$34,$00,$88,$37
	.byte $01,$1f,$1e,$81
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref52:
	.byte $8a,$1f,$1f,$82,$1f,$8a,$1f,$90,$17,$8a,$1f,$1f,$1f,$82,$1f,$8a
	.byte $1f,$1f,$1f,$90,$17,$8a,$1f,$82,$1e,$85
	.byte $ff,$10
	.word @ref52
	.byte $ff,$10
	.word @ref52
@ref55:
	.byte $8a,$1f,$1f,$82,$1f,$8a,$1f,$90,$17,$8a,$1f,$1f,$1f,$82,$1f,$8a
	.byte $1f,$1f,$1f,$90,$16,$85,$17,$16,$81
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
	.byte $fd
	.word @song1ch4loop
