// Metaspriteset generated by mkts [nes mode]
// Copyleft 2017 The Mojon Twins
 
// Cell #0 cut from (0, 0) to (15, 23)

const unsigned char spr_pl_00 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #1 cut from (16, 0) to (31, 23)

const unsigned char spr_pl_01 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #2 cut from (32, 0) to (47, 23)

const unsigned char spr_pl_02 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #3 cut from (48, 0) to (63, 23)

const unsigned char spr_pl_03 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #4 cut from (64, 0) to (79, 23)

const unsigned char spr_pl_04 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #5 cut from (80, 0) to (95, 23)

const unsigned char spr_pl_05 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #6 cut from (0, 24) to (15, 47)

const unsigned char spr_pl_06 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #7 cut from (16, 24) to (31, 47)

const unsigned char spr_pl_07 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #8 cut from (32, 24) to (47, 47)

const unsigned char spr_pl_08 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #9 cut from (48, 24) to (63, 47)

const unsigned char spr_pl_09 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #10 cut from (64, 24) to (79, 47)

const unsigned char spr_pl_0A [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #11 cut from (80, 24) to (95, 47)

const unsigned char spr_pl_0B [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #12 cut from (0, 48) to (15, 71)

const unsigned char spr_pl_0C [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #13 cut from (16, 48) to (31, 71)

const unsigned char spr_pl_0D [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #14 cut from (32, 48) to (47, 71)

const unsigned char spr_pl_0E [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #15 cut from (48, 48) to (63, 71)

const unsigned char spr_pl_0F [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #16 cut from (64, 48) to (79, 71)

const unsigned char spr_pl_10 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #17 cut from (80, 48) to (95, 71)

const unsigned char spr_pl_11 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #18 cut from (0, 72) to (15, 95)

const unsigned char spr_pl_12 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #19 cut from (16, 72) to (31, 95)

const unsigned char spr_pl_13 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #20 cut from (32, 72) to (47, 95)

const unsigned char spr_pl_14 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #21 cut from (48, 72) to (63, 95)

const unsigned char spr_pl_15 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #22 cut from (64, 72) to (79, 95)

const unsigned char spr_pl_16 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #23 cut from (80, 72) to (95, 95)

const unsigned char spr_pl_17 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #24 cut from (0, 96) to (15, 119)

const unsigned char spr_pl_18 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #25 cut from (16, 96) to (31, 119)

const unsigned char spr_pl_19 [] = {
	                                                
	                                                
	                                                
	0x80
};

// 0 patterns used from #0, Next = 0.

