// Metaspriteset generated by mkts [nes mode]
// Copyleft 2017 The Mojon Twins
 
// Cell #0 cut from (0, 0) to (15, 23)

const unsigned char spr_hs1_00 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #1 cut from (16, 0) to (31, 23)

const unsigned char spr_hs1_01 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #2 cut from (32, 0) to (47, 23)

const unsigned char spr_hs1_02 [] = {
	                                                
	                                                
	                                                
	0x80
};

// Cell #3 cut from (48, 0) to (63, 23)

const unsigned char spr_hs1_03 [] = {
	                                                
	                                                
	                                                
	0x80
};

// 0 patterns used from #144, Next = 144.

