// Metaspriteset generated by mkts [nes mode]
// Copyleft 2017 The Mojon Twins
 
// Cell #0 cut from (0, 0) to (15, 15)

const unsigned char spr_hs2_00 [] = {
	                                                
	                                                
	0x80
};

// Cell #1 cut from (16, 0) to (31, 15)

const unsigned char spr_hs2_01 [] = {
	                                                
	                                                
	0x80
};

// Cell #2 cut from (32, 0) to (47, 15)

const unsigned char spr_hs2_02 [] = {
	                                                
	                                                
	0x80
};


// 0 patterns used from #156, Next = 156.

