// Tileset tilemaps & pals generated by mkts [nes mode]
// Copyleft 2015 The Mojon Twins
 
const unsigned char title_pals [] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0
};

const unsigned char title_tmaps [] = {
	216, 216, 216, 216, 
	216, 216, 216, 216, 
	216, 216, 216, 216, 
	216, 216, 216, 216, 
	216, 216, 216, 216, 
	216, 216, 216, 216, 
	216, 216, 216, 216, 
	216, 216, 216, 216, 
	216, 216, 216, 216
};
