// Tileset tilemaps & pals generated by mkts [nes mode]
// Copyleft 2015 The Mojon Twins
 
const unsigned char title_pals [] = {
	2, 2, 2, 2, 2, 2, 2, 2, 2
};

const unsigned char title_tmaps [] = {
	216, 217, 218, 219, 
	220, 221, 222, 222, 
	223, 224, 225, 226, 
	227, 228, 229, 230, 
	227, 228, 229, 230, 
	231, 232, 233, 234, 
	220, 221, 222, 222, 
	235, 236, 237, 238, 
	239, 240, 241, 242
};
