// rle53mapMK1(TM) map map0.h
// Generated by rle53mapMK1.exe
// Copyleft 2015, 2017, 2018 The Mojon Twins

// Map Size Is 4x6
// Screen Size Is 16x12

// [binmode] - This file contains only constants.
// Actual map index + map binary + locks is in map0.h.bin

#define MAP_0_MAP_W        4
#define MAP_0_MAP_H        6
#define MAP_0_MAP_SIZE     24
#define MAP_0_MAP_BYTES    0x0553


#define N_BOLTS_0 2

#define MAP_0_BOLTS_OFFSET 0x0553
#define MAP_0_BOLTS_BYTES  4
