// CHR-ROM Map & decos indexes
// Generated by rle53mapchrrom.exe v0.2 20180625
// Copyleft 2017, 2018 by The Mojon Twins

// Map # 0 read from level0.map (6x4)

// Definitions

#define MAP_00_CHRROM    3
#define MAP_00_BASE      0x0000
#define MAP_00_W         6
#define MAP_00_H         4
#define MAP_00_MAXPANTS  24
#define MAP_00_N_LOCKS   4

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0027, 
	MAP_00_BASE + 0x0058, MAP_00_BASE + 0x00CD, 
	MAP_00_BASE + 0x0147, MAP_00_BASE + 0x01C7, 
	MAP_00_BASE + 0x01F7, MAP_00_BASE + 0x022D, 
	MAP_00_BASE + 0x02AA, MAP_00_BASE + 0x031E, 
	MAP_00_BASE + 0x0387, MAP_00_BASE + 0x0405, 
	MAP_00_BASE + 0x047E, MAP_00_BASE + 0x04AA, 
	MAP_00_BASE + 0x0516, MAP_00_BASE + 0x0584, 
	MAP_00_BASE + 0x0600, MAP_00_BASE + 0x0661, 
	MAP_00_BASE + 0x06D4, MAP_00_BASE + 0x072C, 
	MAP_00_BASE + 0x07B8, MAP_00_BASE + 0x0829, 
	MAP_00_BASE + 0x08AD, MAP_00_BASE + 0x0909
};

// Total screens size in bytes is 2411

// Locks
// These tiles are locks:  15
const unsigned char map_00_locks [] = {
	0x15, 0xaf, 0x16, 0xaf
};

// Map # 1 read from level1.map (8x3)

// Definitions

#define MAP_01_CHRROM    3
#define MAP_01_BASE      0x096B
#define MAP_01_W         8
#define MAP_01_H         3
#define MAP_01_MAXPANTS  24
#define MAP_01_N_LOCKS   0

// Screens index

const unsigned int map_01_scr_offsets [] = {
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x0054, 
	MAP_01_BASE + 0x0090, MAP_01_BASE + 0x00CA, 
	MAP_01_BASE + 0x0106, MAP_01_BASE + 0x014F, 
	MAP_01_BASE + 0x0198, MAP_01_BASE + 0x01EE, 
	MAP_01_BASE + 0x0246, MAP_01_BASE + 0x0291, 
	MAP_01_BASE + 0x02C8, MAP_01_BASE + 0x0324, 
	MAP_01_BASE + 0x038B, MAP_01_BASE + 0x03CE, 
	MAP_01_BASE + 0x041C, MAP_01_BASE + 0x045B, 
	MAP_01_BASE + 0x049C, MAP_01_BASE + 0x04F1, 
	MAP_01_BASE + 0x053B, MAP_01_BASE + 0x0594, 
	MAP_01_BASE + 0x05D2, MAP_01_BASE + 0x0620, 
	MAP_01_BASE + 0x0672, MAP_01_BASE + 0x06CD
};

// Total screens size in bytes is 1791

// Map # 2 read from level2.map (6x4)

// Definitions

#define MAP_02_CHRROM    3
#define MAP_02_BASE      0x106A
#define MAP_02_W         6
#define MAP_02_H         4
#define MAP_02_MAXPANTS  24
#define MAP_02_N_LOCKS   0

// Screens index

const unsigned int map_02_scr_offsets [] = {
	MAP_02_BASE + 0x0000, MAP_02_BASE + 0x0037, 
	MAP_02_BASE + 0x0064, MAP_02_BASE + 0x00A7, 
	MAP_02_BASE + 0x00DF, MAP_02_BASE + 0x0127, 
	MAP_02_BASE + 0x0181, MAP_02_BASE + 0x01B9, 
	MAP_02_BASE + 0x0221, MAP_02_BASE + 0x027A, 
	MAP_02_BASE + 0x02EA, MAP_02_BASE + 0x034C, 
	MAP_02_BASE + 0x039B, MAP_02_BASE + 0x03F7, 
	MAP_02_BASE + 0x044F, MAP_02_BASE + 0x04BE, 
	MAP_02_BASE + 0x0526, MAP_02_BASE + 0x057B, 
	MAP_02_BASE + 0x05D9, MAP_02_BASE + 0x0617, 
	MAP_02_BASE + 0x0689, MAP_02_BASE + 0x06E4, 
	MAP_02_BASE + 0x0722, MAP_02_BASE + 0x0788
};

// Total screens size in bytes is 2031

// Map # 3 read from level3.map (4x6)

// Definitions

#define MAP_03_CHRROM    3
#define MAP_03_BASE      0x1859
#define MAP_03_W         4
#define MAP_03_H         6
#define MAP_03_MAXPANTS  24
#define MAP_03_N_LOCKS   4

// Screens index

const unsigned int map_03_scr_offsets [] = {
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x0036, 
	MAP_03_BASE + 0x0074, MAP_03_BASE + 0x0097, 
	MAP_03_BASE + 0x00C3, MAP_03_BASE + 0x00F6, 
	MAP_03_BASE + 0x013F, MAP_03_BASE + 0x0166, 
	MAP_03_BASE + 0x019B, MAP_03_BASE + 0x01E1, 
	MAP_03_BASE + 0x021C, MAP_03_BASE + 0x0253, 
	MAP_03_BASE + 0x0290, MAP_03_BASE + 0x02C1, 
	MAP_03_BASE + 0x02F6, MAP_03_BASE + 0x0331, 
	MAP_03_BASE + 0x0367, MAP_03_BASE + 0x03A4, 
	MAP_03_BASE + 0x03CA, MAP_03_BASE + 0x0407, 
	MAP_03_BASE + 0x0440, MAP_03_BASE + 0x047C, 
	MAP_03_BASE + 0x04AB, MAP_03_BASE + 0x04E4
};

// Total screens size in bytes is 1315

// Locks
// These tiles are locks:  15
const unsigned char map_03_locks [] = {
	0x00, 0x8b, 0x12, 0x83
};

// Map # 4 read from level4.map (6x2)

// Definitions

#define MAP_04_CHRROM    3
#define MAP_04_BASE      0x1D7C
#define MAP_04_W         6
#define MAP_04_H         2
#define MAP_04_MAXPANTS  12
#define MAP_04_N_LOCKS   0

// Screens index

const unsigned int map_04_scr_offsets [] = {
	MAP_04_BASE + 0x0000, MAP_04_BASE + 0x0034, 
	MAP_04_BASE + 0x0068, MAP_04_BASE + 0x0094, 
	MAP_04_BASE + 0x00B7, MAP_04_BASE + 0x00DF, 
	0                   , 0                   , 
	0                   , 0                   , 
	0                   , MAP_04_BASE + 0x0119
};

// Total screens size in bytes is 344

