// rle44mapMK1(TM) map ..\dev\assets\map2.h
// Generated by rle44mapMK1.exe
// Copyleft 2015, 2017, 2018 The Mojon Twins

// Map Size Is 8x3
// Screen Size Is 16x12

// Compressed map structure, screens in RLE44, byte = NNNNRRRR, repeat R times tile #N
// Decos follow each screen, Format: [T N YX YX YX YX... (T < 128) | T YX (T >= 128)]

// Screen 00 is empty.
// Screen 01 is empty.
// Screen 02 is empty.
// Screen 03 is empty.
// Screen 04 is empty.
// Screen 05 is empty.
// Screen 06 is empty.
// Screen 07 is empty.
const unsigned char scr_2_08 [] = {0x26, 0x0b, 0x74, 0x0b, 0x24, 0x16, 0x02, 0x05, 0x42, 0x20, 0x05, 0x22, 0x06, 0x12, 0x05, 0x22, 0x40, 0x0b, 0x22, 0x09, 0x12, 0x05, 0x12, 0x70, 0x12, 0x09, 0x12, 0x05, 0xa0, 0x02, 0x06, 0x02, 0x00, 0x05, 0xb0, 0x09, 0x10, 0x0b, 0x34, 0x0b, 0x10, 0x0b, 0x34, 0x06, 0x10, 0x62, 0x0a, 0x05, 0x38, 0x06, 0x00, 0x82, 0x05, 0x38, 0x06, 0x92, 0x0b, 0x38, 0x19, 0x47, 0x26, 0x07, 0x09, 0x37, 0x16, 0x19, 0x07, 0x19, 0x16, 0x39, 0x27, 0xa9, 0x3c, 0xa7, 0x74, 0xa8, 0x77, 0x00};
// Size = 78 bytes.
const unsigned char scr_2_09 [] = {0xf0, 0xf0, 0xf0, 0xf0, 0x50, 0x0f, 0xf0, 0xf0, 0xf0, 0xf0, 0xf0, 0xf0, 0xf0, 0x80, 0x00};
// Size = 15 bytes.
// Screen 0a is empty.
// Screen 0b is empty.
// Screen 0c is empty.
// Screen 0d is empty.
// Screen 0e is empty.
// Screen 0f is empty.
// Screen 10 is empty.
// Screen 11 is empty.
// Screen 12 is empty.
// Screen 13 is empty.
// Screen 14 is empty.
// Screen 15 is empty.
// Screen 16 is empty.
// Screen 17 is empty.

// Compressed map array

const unsigned char * const map_2 [] = {
	       0,        0,        0,        0,        0,        0,        0,        0, 
	scr_2_08, scr_2_09,        0,        0,        0,        0,        0,        0, 
	       0,        0,        0,        0,        0,        0,        0,        0
};

// Total map size in bytes is 141
// From which, decorations size in bytes is 30

// Locks
// Format: NP YX ...

#define N_BOLTS_2 1

const unsigned char map_2_locks [] = {
	0x09, 0x46
};

