// CHR-ROM Map & decos indexes
// Generated by rle44mapchrrom.exe v0.2 20180625
// Copyleft 2017, 2018 by The Mojon Twins

// Map # 0 read from level00.map (10x3)

// Definitions

#define MAP_00_CHRROM    2
#define MAP_00_BASE      0x0000
#define MAP_00_W         10
#define MAP_00_H         3
#define MAP_00_MAXPANTS  30
#define MAP_00_N_LOCKS   0

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x000C, 
	MAP_00_BASE + 0x001B, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0034, MAP_00_BASE + 0x0069, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x008E, 
	MAP_00_BASE + 0x00C5, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x00F5, MAP_00_BASE + 0x013B, 
	MAP_00_BASE + 0x0168, MAP_00_BASE + 0x01A9, 
	MAP_00_BASE + 0x01D7, MAP_00_BASE + 0x0216, 
	MAP_00_BASE + 0x023E, MAP_00_BASE + 0x026D, 
	MAP_00_BASE + 0x028F, MAP_00_BASE + 0x02BE
};

// Total screens size in bytes is 760

// Map # 1 read from level01.map (10x3)

// Definitions

#define MAP_01_CHRROM    2
#define MAP_01_BASE      0x02F8
#define MAP_01_W         10
#define MAP_01_H         3
#define MAP_01_MAXPANTS  30
#define MAP_01_N_LOCKS   0

// Screens index

const unsigned int map_01_scr_offsets [] = {
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x0047, 
	MAP_01_BASE + 0x0092, MAP_01_BASE + 0x00DA, 
	MAP_01_BASE + 0x0102, MAP_01_BASE + 0x0137, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x016A, MAP_01_BASE + 0x0199, 
	MAP_01_BASE + 0x01C8, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x020D, MAP_01_BASE + 0x0257, 
	MAP_01_BASE + 0x0290, MAP_01_BASE + 0x02AE, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x02D1, 
	MAP_01_BASE + 0x02F8, MAP_01_BASE + 0x0321, 
	MAP_01_BASE + 0x0336, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x0360, 
	MAP_01_BASE + 0x03A5, MAP_01_BASE + 0x03D0
};

// Total screens size in bytes is 1022

// Map # 2 read from level02.map (3x1)

// Definitions

#define MAP_02_CHRROM    2
#define MAP_02_BASE      0x06F6
#define MAP_02_W         3
#define MAP_02_H         1
#define MAP_02_MAXPANTS  3
#define MAP_02_N_LOCKS   0

// Screens index

const unsigned int map_02_scr_offsets [] = {
	MAP_02_BASE + 0x0000, MAP_02_BASE + 0x004A, 
	MAP_02_BASE + 0x0097
};

// Total screens size in bytes is 220

// Map # 3 read from level10.map (15x2)

// Definitions

#define MAP_03_CHRROM    2
#define MAP_03_BASE      0x07D2
#define MAP_03_W         15
#define MAP_03_H         2
#define MAP_03_MAXPANTS  30
#define MAP_03_N_LOCKS   0

// Screens index

const unsigned int map_03_scr_offsets [] = {
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x0000, 
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x000C, 
	MAP_03_BASE + 0x001C, MAP_03_BASE + 0x0036, 
	MAP_03_BASE + 0x006C, MAP_03_BASE + 0x009C, 
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x0000, 
	MAP_03_BASE + 0x00A9, MAP_03_BASE + 0x0000, 
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x0000, 
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x00BC, 
	MAP_03_BASE + 0x00D6, MAP_03_BASE + 0x0102, 
	MAP_03_BASE + 0x015B, MAP_03_BASE + 0x01BC, 
	MAP_03_BASE + 0x01E9, MAP_03_BASE + 0x0217, 
	MAP_03_BASE + 0x0250, MAP_03_BASE + 0x0288, 
	MAP_03_BASE + 0x02B6, MAP_03_BASE + 0x02CF, 
	MAP_03_BASE + 0x0306, MAP_03_BASE + 0x0336, 
	MAP_03_BASE + 0x035D, MAP_03_BASE + 0x0385
};

// Total screens size in bytes is 936

// Map # 4 read from level11.map (25x1)

// Definitions

#define MAP_04_CHRROM    2
#define MAP_04_BASE      0x0B7A
#define MAP_04_W         25
#define MAP_04_H         1
#define MAP_04_MAXPANTS  25
#define MAP_04_N_LOCKS   0

// Screens index

const unsigned int map_04_scr_offsets [] = {
	MAP_04_BASE + 0x0000, MAP_04_BASE + 0x0033, 
	MAP_04_BASE + 0x0062, MAP_04_BASE + 0x008A, 
	MAP_04_BASE + 0x00B2, MAP_04_BASE + 0x00F0, 
	MAP_04_BASE + 0x0138, MAP_04_BASE + 0x0175, 
	MAP_04_BASE + 0x01A7, MAP_04_BASE + 0x01E1, 
	MAP_04_BASE + 0x01FE, MAP_04_BASE + 0x0232, 
	MAP_04_BASE + 0x0261, MAP_04_BASE + 0x02A4, 
	MAP_04_BASE + 0x02DD, MAP_04_BASE + 0x0326, 
	MAP_04_BASE + 0x0377, MAP_04_BASE + 0x0393, 
	MAP_04_BASE + 0x03CE, MAP_04_BASE + 0x040D, 
	MAP_04_BASE + 0x043F, MAP_04_BASE + 0x0479, 
	MAP_04_BASE + 0x04B0, MAP_04_BASE + 0x04CB, 
	MAP_04_BASE + 0x04EA
};

// Total screens size in bytes is 1313

// Map # 5 read from level20.map (1x20)

// Definitions

#define MAP_05_CHRROM    2
#define MAP_05_BASE      0x109B
#define MAP_05_W         1
#define MAP_05_H         20
#define MAP_05_MAXPANTS  20
#define MAP_05_N_LOCKS   0

// Screens index

const unsigned int map_05_scr_offsets [] = {
	MAP_05_BASE + 0x0000, MAP_05_BASE + 0x0059, 
	MAP_05_BASE + 0x00A6, MAP_05_BASE + 0x00E8, 
	MAP_05_BASE + 0x012A, MAP_05_BASE + 0x0169, 
	MAP_05_BASE + 0x01A7, MAP_05_BASE + 0x020E, 
	MAP_05_BASE + 0x0259, MAP_05_BASE + 0x0289, 
	MAP_05_BASE + 0x02C6, MAP_05_BASE + 0x030C, 
	MAP_05_BASE + 0x0347, MAP_05_BASE + 0x038A, 
	MAP_05_BASE + 0x03CA, MAP_05_BASE + 0x0407, 
	MAP_05_BASE + 0x0448, MAP_05_BASE + 0x0484, 
	MAP_05_BASE + 0x04C5, MAP_05_BASE + 0x0509
};

// Total screens size in bytes is 1348

// Map # 6 read from level30.map (4x5)

// Definitions

#define MAP_06_CHRROM    2
#define MAP_06_BASE      0x15DF
#define MAP_06_W         4
#define MAP_06_H         5
#define MAP_06_MAXPANTS  20
#define MAP_06_N_LOCKS   0

// Screens index

const unsigned int map_06_scr_offsets [] = {
	MAP_06_BASE + 0x0000, MAP_06_BASE + 0x005A, 
	MAP_06_BASE + 0x0095, MAP_06_BASE + 0x00CE, 
	MAP_06_BASE + 0x013E, MAP_06_BASE + 0x019E, 
	MAP_06_BASE + 0x01E6, MAP_06_BASE + 0x0249, 
	MAP_06_BASE + 0x0282, MAP_06_BASE + 0x02D3, 
	MAP_06_BASE + 0x031E, MAP_06_BASE + 0x0367, 
	MAP_06_BASE + 0x03C5, MAP_06_BASE + 0x040B, 
	MAP_06_BASE + 0x0434, MAP_06_BASE + 0x048A, 
	MAP_06_BASE + 0x04D4, MAP_06_BASE + 0x0520, 
	MAP_06_BASE + 0x055E, MAP_06_BASE + 0x05A7
};

// Total screens size in bytes is 1520

