// CHR-ROM Map & decos indexes
// Generated by rle44mapchrrom.exe v0.2 20180625
// Copyleft 2017, 2018 by The Mojon Twins

// Map # 0 read from level01.map (10x3)

// Definitions

#define MAP_01_CHRROM    2
#define MAP_01_BASE      0x0000
#define MAP_01_W         10
#define MAP_01_H         3
#define MAP_01_MAXPANTS  30
#define MAP_01_N_LOCKS   0

// Screens index

const unsigned int map_01_scr_offsets [] = {
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x0047, 
	MAP_01_BASE + 0x0092, MAP_01_BASE + 0x00DA, 
	MAP_01_BASE + 0x0102, MAP_01_BASE + 0x0137, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x016A, MAP_01_BASE + 0x0199, 
	MAP_01_BASE + 0x01C8, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x020D, MAP_01_BASE + 0x0257, 
	MAP_01_BASE + 0x0290, MAP_01_BASE + 0x02AE, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x02D1, 
	MAP_01_BASE + 0x02F8, MAP_01_BASE + 0x0321, 
	MAP_01_BASE + 0x0336, MAP_01_BASE + 0x015E, 
	MAP_01_BASE + 0x015E, MAP_01_BASE + 0x0360, 
	MAP_01_BASE + 0x03A5, MAP_01_BASE + 0x03D0
};

// Total screens size in bytes is 1022

// Map # 1 read from level10.map (15x2)

// Definitions

#define MAP_10_CHRROM    2
#define MAP_10_BASE      0x03FE
#define MAP_10_W         15
#define MAP_10_H         2
#define MAP_10_MAXPANTS  30
#define MAP_10_N_LOCKS   0

// Screens index

const unsigned int map_10_scr_offsets [] = {
	MAP_10_BASE + 0x0000, MAP_10_BASE + 0x0000, 
	MAP_10_BASE + 0x0000, MAP_10_BASE + 0x000C, 
	MAP_10_BASE + 0x001C, MAP_10_BASE + 0x0036, 
	MAP_10_BASE + 0x006C, MAP_10_BASE + 0x009B, 
	MAP_10_BASE + 0x0000, MAP_10_BASE + 0x0000, 
	MAP_10_BASE + 0x00A8, MAP_10_BASE + 0x0000, 
	MAP_10_BASE + 0x0000, MAP_10_BASE + 0x0000, 
	MAP_10_BASE + 0x0000, MAP_10_BASE + 0x00BA, 
	MAP_10_BASE + 0x00D4, MAP_10_BASE + 0x00FE, 
	MAP_10_BASE + 0x0157, MAP_10_BASE + 0x01B5, 
	MAP_10_BASE + 0x01E2, MAP_10_BASE + 0x0210, 
	MAP_10_BASE + 0x0236, MAP_10_BASE + 0x026E, 
	MAP_10_BASE + 0x029C, MAP_10_BASE + 0x02B5, 
	MAP_10_BASE + 0x02E3, MAP_10_BASE + 0x0313, 
	MAP_10_BASE + 0x033B, MAP_10_BASE + 0x0363
};

// Total screens size in bytes is 899

// Map # 2 read from level11.map (25x1)

// Definitions

#define MAP_11_CHRROM    2
#define MAP_11_BASE      0x0781
#define MAP_11_W         25
#define MAP_11_H         1
#define MAP_11_MAXPANTS  25
#define MAP_11_N_LOCKS   0

// Screens index

const unsigned int map_11_scr_offsets [] = {
	MAP_11_BASE + 0x0000, MAP_11_BASE + 0x002A, 
	MAP_11_BASE + 0x0049, MAP_11_BASE + 0x0069, 
	MAP_11_BASE + 0x008A, MAP_11_BASE + 0x00CC, 
	MAP_11_BASE + 0x010D, MAP_11_BASE + 0x0145, 
	MAP_11_BASE + 0x016C, MAP_11_BASE + 0x019F, 
	MAP_11_BASE + 0x01D0, MAP_11_BASE + 0x0203, 
	MAP_11_BASE + 0x0230, MAP_11_BASE + 0x026B, 
	MAP_11_BASE + 0x02A4, MAP_11_BASE + 0x02CF, 
	MAP_11_BASE + 0x031B, MAP_11_BASE + 0x0330, 
	MAP_11_BASE + 0x036B, MAP_11_BASE + 0x039F, 
	MAP_11_BASE + 0x03CE, MAP_11_BASE + 0x0408, 
	MAP_11_BASE + 0x043C, MAP_11_BASE + 0x044E, 
	MAP_11_BASE + 0x046D
};

// Total screens size in bytes is 1188

// Map # 3 read from level20.map (1x20)

// Definitions

#define MAP_20_CHRROM    2
#define MAP_20_BASE      0x0C25
#define MAP_20_W         1
#define MAP_20_H         20
#define MAP_20_MAXPANTS  20
#define MAP_20_N_LOCKS   0

// Screens index

const unsigned int map_20_scr_offsets [] = {
	MAP_20_BASE + 0x0000, MAP_20_BASE + 0x0049, 
	MAP_20_BASE + 0x0092, MAP_20_BASE + 0x00CE, 
	MAP_20_BASE + 0x010A, MAP_20_BASE + 0x013E, 
	MAP_20_BASE + 0x0172, MAP_20_BASE + 0x01D6, 
	MAP_20_BASE + 0x0220, MAP_20_BASE + 0x024D, 
	MAP_20_BASE + 0x0285, MAP_20_BASE + 0x02C5, 
	MAP_20_BASE + 0x02FA, MAP_20_BASE + 0x033C, 
	MAP_20_BASE + 0x0379, MAP_20_BASE + 0x03AE, 
	MAP_20_BASE + 0x03EC, MAP_20_BASE + 0x042E, 
	MAP_20_BASE + 0x046D, MAP_20_BASE + 0x04A8
};

// Total screens size in bytes is 1240

// Map # 4 read from level21.map (15x2)

// Definitions

#define MAP_21_CHRROM    2
#define MAP_21_BASE      0x10FD
#define MAP_21_W         15
#define MAP_21_H         2
#define MAP_21_MAXPANTS  30
#define MAP_21_N_LOCKS   0

// Screens index

const unsigned int map_21_scr_offsets [] = {
	MAP_21_BASE + 0x0000, MAP_21_BASE + 0x0000, 
	MAP_21_BASE + 0x0000, MAP_21_BASE + 0x000C, 
	MAP_21_BASE + 0x002A, MAP_21_BASE + 0x006F, 
	MAP_21_BASE + 0x009B, MAP_21_BASE + 0x00BD, 
	MAP_21_BASE + 0x00D7, MAP_21_BASE + 0x00F4, 
	MAP_21_BASE + 0x0000, MAP_21_BASE + 0x0000, 
	MAP_21_BASE + 0x010E, MAP_21_BASE + 0x0000, 
	MAP_21_BASE + 0x0000, MAP_21_BASE + 0x0137, 
	MAP_21_BASE + 0x0196, MAP_21_BASE + 0x01E3, 
	MAP_21_BASE + 0x020D, MAP_21_BASE + 0x0000, 
	MAP_21_BASE + 0x0000, MAP_21_BASE + 0x0252, 
	MAP_21_BASE + 0x0277, MAP_21_BASE + 0x0000, 
	MAP_21_BASE + 0x02AE, MAP_21_BASE + 0x02C6, 
	MAP_21_BASE + 0x0313, MAP_21_BASE + 0x034B, 
	MAP_21_BASE + 0x037D, MAP_21_BASE + 0x0397
};

// Total screens size in bytes is 949

// Map # 5 read from level30.map (5x5)

// Definitions

#define MAP_30_CHRROM    2
#define MAP_30_BASE      0x14B2
#define MAP_30_W         5
#define MAP_30_H         5
#define MAP_30_MAXPANTS  25
#define MAP_30_N_LOCKS   0

// Screens index

const unsigned int map_30_scr_offsets [] = {
	MAP_30_BASE + 0x0000, MAP_30_BASE + 0x002F, 
	0                   , 0                   , 
	0                   , MAP_30_BASE + 0x0063, 
	MAP_30_BASE + 0x009C, 0                   , 
	MAP_30_BASE + 0x00EA, MAP_30_BASE + 0x0129, 
	MAP_30_BASE + 0x0153, MAP_30_BASE + 0x01B7, 
	MAP_30_BASE + 0x01EF, MAP_30_BASE + 0x0250, 
	0                   , MAP_30_BASE + 0x0297, 
	MAP_30_BASE + 0x02DF, MAP_30_BASE + 0x031B, 
	MAP_30_BASE + 0x0375, 0                   , 
	0                   , MAP_30_BASE + 0x03AE, 
	MAP_30_BASE + 0x03EB, MAP_30_BASE + 0x042E, 
	0                   
};

// Total screens size in bytes is 1140

// Map # 6 read from level31.map (5x5)

// Definitions

#define MAP_31_CHRROM    2
#define MAP_31_BASE      0x1926
#define MAP_31_W         5
#define MAP_31_H         5
#define MAP_31_MAXPANTS  25
#define MAP_31_N_LOCKS   0

// Screens index

const unsigned int map_31_scr_offsets [] = {
	MAP_31_BASE + 0x0000, MAP_31_BASE + 0x0034, 
	MAP_31_BASE + 0x004F, MAP_31_BASE + 0x0083, 
	MAP_31_BASE + 0x00B9, MAP_31_BASE + 0x00DE, 
	MAP_31_BASE + 0x010A, MAP_31_BASE + 0x0139, 
	MAP_31_BASE + 0x0184, MAP_31_BASE + 0x01CB, 
	MAP_31_BASE + 0x01E6, MAP_31_BASE + 0x0218, 
	MAP_31_BASE + 0x0261, MAP_31_BASE + 0x02B6, 
	MAP_31_BASE + 0x02F6, MAP_31_BASE + 0x0318, 
	MAP_31_BASE + 0x0354, MAP_31_BASE + 0x03A1, 
	MAP_31_BASE + 0x03F0, 0                   , 
	MAP_31_BASE + 0x0437, MAP_31_BASE + 0x045F, 
	MAP_31_BASE + 0x0480, MAP_31_BASE + 0x04B0, 
	0                   
};

// Total screens size in bytes is 1244

// Map # 7 read from level02.map (3x1)

// Definitions

#define MAP_02_CHRROM    2
#define MAP_02_BASE      0x1E02
#define MAP_02_W         3
#define MAP_02_H         1
#define MAP_02_MAXPANTS  3
#define MAP_02_N_LOCKS   0

// Screens index

const unsigned int map_02_scr_offsets [] = {
	MAP_02_BASE + 0x0000, MAP_02_BASE + 0x0040, 
	MAP_02_BASE + 0x008D
};

// Total screens size in bytes is 192

// Map # 8 read from level12.map (3x1)

// Definitions

#define MAP_12_CHRROM    2
#define MAP_12_BASE      0x1EC2
#define MAP_12_W         3
#define MAP_12_H         1
#define MAP_12_MAXPANTS  3
#define MAP_12_N_LOCKS   0

// Screens index

const unsigned int map_12_scr_offsets [] = {
	MAP_12_BASE + 0x0000, MAP_12_BASE + 0x001E, 
	MAP_12_BASE + 0x0033
};

// Total screens size in bytes is 90

// Map # 9 read from level22.map (1x3)

// Definitions

#define MAP_22_CHRROM    2
#define MAP_22_BASE      0x1F1C
#define MAP_22_W         1
#define MAP_22_H         3
#define MAP_22_MAXPANTS  3
#define MAP_22_N_LOCKS   0

// Screens index

const unsigned int map_22_scr_offsets [] = {
	MAP_22_BASE + 0x0000, MAP_22_BASE + 0x0020, 
	MAP_22_BASE + 0x0051
};

// Total screens size in bytes is 128

// Map # 10 read from level00.map (10x3)

// Definitions

#define MAP_00_CHRROM    3
#define MAP_00_BASE      0x0000
#define MAP_00_W         10
#define MAP_00_H         3
#define MAP_00_MAXPANTS  30
#define MAP_00_N_LOCKS   0

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x000C, 
	MAP_00_BASE + 0x001B, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x0034, MAP_00_BASE + 0x0069, 
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x008E, 
	MAP_00_BASE + 0x00C5, MAP_00_BASE + 0x0000, 
	MAP_00_BASE + 0x00F5, MAP_00_BASE + 0x013B, 
	MAP_00_BASE + 0x0168, MAP_00_BASE + 0x01A9, 
	MAP_00_BASE + 0x01D7, MAP_00_BASE + 0x0216, 
	MAP_00_BASE + 0x023E, MAP_00_BASE + 0x026D, 
	MAP_00_BASE + 0x028F, MAP_00_BASE + 0x02BE
};

// Total screens size in bytes is 760

// Map # 11 read from level32.map (2x1)

// Definitions

#define MAP_32_CHRROM    3
#define MAP_32_BASE      0x02F8
#define MAP_32_W         2
#define MAP_32_H         1
#define MAP_32_MAXPANTS  2
#define MAP_32_N_LOCKS   0

// Screens index

const unsigned int map_32_scr_offsets [] = {
	MAP_32_BASE + 0x0000, MAP_32_BASE + 0x003A
};

// Total screens size in bytes is 111

// Map # 12 read from level40.map (15x2)

// Definitions

#define MAP_40_CHRROM    3
#define MAP_40_BASE      0x0367
#define MAP_40_W         15
#define MAP_40_H         2
#define MAP_40_MAXPANTS  30
#define MAP_40_N_LOCKS   0

// Screens index

const unsigned int map_40_scr_offsets [] = {
	0                   , 0                   , 
	0                   , MAP_40_BASE + 0x0000, 
	MAP_40_BASE + 0x0039, MAP_40_BASE + 0x006A, 
	0                   , 0                   , 
	MAP_40_BASE + 0x00A1, MAP_40_BASE + 0x00DB, 
	MAP_40_BASE + 0x00F6, MAP_40_BASE + 0x010C, 
	MAP_40_BASE + 0x012D, MAP_40_BASE + 0x013E, 
	MAP_40_BASE + 0x0156, MAP_40_BASE + 0x0185, 
	MAP_40_BASE + 0x01B6, MAP_40_BASE + 0x01E2, 
	MAP_40_BASE + 0x0212, MAP_40_BASE + 0x023D, 
	MAP_40_BASE + 0x026F, MAP_40_BASE + 0x0283, 
	MAP_40_BASE + 0x02B2, MAP_40_BASE + 0x02DD, 
	0                   , MAP_40_BASE + 0x031B, 
	MAP_40_BASE + 0x031B, 0                   , 
	0                   , 0                   
};

// Total screens size in bytes is 860

// Map # 13 read from level41.map (5x5)

// Definitions

#define MAP_41_CHRROM    3
#define MAP_41_BASE      0x06C3
#define MAP_41_W         5
#define MAP_41_H         5
#define MAP_41_MAXPANTS  25
#define MAP_41_N_LOCKS   0

// Screens index

const unsigned int map_41_scr_offsets [] = {
	0                   , MAP_41_BASE + 0x0000, 
	MAP_41_BASE + 0x0024, MAP_41_BASE + 0x004B, 
	MAP_41_BASE + 0x0067, 0                   , 
	MAP_41_BASE + 0x0082, MAP_41_BASE + 0x0024, 
	MAP_41_BASE + 0x00B4, MAP_41_BASE + 0x00E7, 
	0                   , MAP_41_BASE + 0x0000, 
	MAP_41_BASE + 0x0024, MAP_41_BASE + 0x00B4, 
	MAP_41_BASE + 0x00E7, 0                   , 
	MAP_41_BASE + 0x0082, MAP_41_BASE + 0x0024, 
	MAP_41_BASE + 0x00B4, MAP_41_BASE + 0x00E7, 
	MAP_41_BASE + 0x0136, MAP_41_BASE + 0x0154, 
	MAP_41_BASE + 0x0165, MAP_41_BASE + 0x017E, 
	MAP_41_BASE + 0x019F
};

// Total screens size in bytes is 461

// Map # 14 read from level42.map (3x1)

// Definitions

#define MAP_42_CHRROM    3
#define MAP_42_BASE      0x0890
#define MAP_42_W         3
#define MAP_42_H         1
#define MAP_42_MAXPANTS  3
#define MAP_42_N_LOCKS   0

// Screens index

const unsigned int map_42_scr_offsets [] = {
	MAP_42_BASE + 0x0000, MAP_42_BASE + 0x0034, 
	MAP_42_BASE + 0x006E
};

// Total screens size in bytes is 152

