// Index file to work\enems.bin
// Generated by binpaster.exe v0.1 20180405
// Copyleft 2018 by The Mojon Twins

#define WORK_ENEMS00_H_BIN_OFFS 0
#define WORK_ENEMS01_H_BIN_OFFS 420
#define WORK_ENEMS02_H_BIN_OFFS 840
#define WORK_ENEMS10_H_BIN_OFFS 882
#define WORK_ENEMS11_H_BIN_OFFS 1302
#define WORK_ENEMS12_H_BIN_OFFS 1652

