// Index file to work\enems.bin
// Generated by binpaster.exe v0.1 20180405
// Copyleft 2018 by The Mojon Twins

#define WORK_ENEMS00_H_BIN_OFFS 0
#define WORK_ENEMS01_H_BIN_OFFS 420
#define WORK_ENEMS02_H_BIN_OFFS 840

